# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/blogin/PycharmProjects/DMT-git/src/ui/ui_initialize_hw_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HwInitializeDlg(object):
    def setupUi(self, HwInitializeDlg):
        HwInitializeDlg.setObjectName("HwInitializeDlg")
        HwInitializeDlg.resize(598, 446)
        self.verticalLayout = QtWidgets.QVBoxLayout(HwInitializeDlg)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabSteps = QtWidgets.QStackedWidget(HwInitializeDlg)
        self.tabSteps.setObjectName("tabSteps")
        self.pgStepDeviceType = QtWidgets.QWidget()
        self.pgStepDeviceType.setObjectName("pgStepDeviceType")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pgStepDeviceType)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lblStepDeviceType = QtWidgets.QLabel(self.pgStepDeviceType)
        self.lblStepDeviceType.setOpenExternalLinks(True)
        self.lblStepDeviceType.setObjectName("lblStepDeviceType")
        self.verticalLayout_12.addWidget(self.lblStepDeviceType)
        self.gbDeviceType = QtWidgets.QGroupBox(self.pgStepDeviceType)
        self.gbDeviceType.setTitle("")
        self.gbDeviceType.setObjectName("gbDeviceType")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.gbDeviceType)
        self.verticalLayout_14.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_14.setSpacing(8)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.rbDeviceTrezor = QtWidgets.QRadioButton(self.gbDeviceType)
        self.rbDeviceTrezor.setObjectName("rbDeviceTrezor")
        self.verticalLayout_14.addWidget(self.rbDeviceTrezor)
        self.rbDeviceKeepkey = QtWidgets.QRadioButton(self.gbDeviceType)
        self.rbDeviceKeepkey.setObjectName("rbDeviceKeepkey")
        self.verticalLayout_14.addWidget(self.rbDeviceKeepkey)
        self.rbDeviceLedger = QtWidgets.QRadioButton(self.gbDeviceType)
        self.rbDeviceLedger.setObjectName("rbDeviceLedger")
        self.verticalLayout_14.addWidget(self.rbDeviceLedger)
        self.verticalLayout_12.addWidget(self.gbDeviceType)
        self.lblStepDeviceTypeMessage = QtWidgets.QLabel(self.pgStepDeviceType)
        self.lblStepDeviceTypeMessage.setText("")
        self.lblStepDeviceTypeMessage.setWordWrap(True)
        self.lblStepDeviceTypeMessage.setOpenExternalLinks(False)
        self.lblStepDeviceTypeMessage.setObjectName("lblStepDeviceTypeMessage")
        self.verticalLayout_12.addWidget(self.lblStepDeviceTypeMessage)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem)
        self.tabSteps.addWidget(self.pgStepDeviceType)
        self.pgStepDeviceInstance = QtWidgets.QWidget()
        self.pgStepDeviceInstance.setObjectName("pgStepDeviceInstance")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pgStepDeviceInstance)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lblStepDeviceInstanceMessage = QtWidgets.QLabel(self.pgStepDeviceInstance)
        self.lblStepDeviceInstanceMessage.setWordWrap(True)
        self.lblStepDeviceInstanceMessage.setObjectName("lblStepDeviceInstanceMessage")
        self.verticalLayout_15.addWidget(self.lblStepDeviceInstanceMessage)
        self.cboDeviceInstance = QtWidgets.QComboBox(self.pgStepDeviceInstance)
        self.cboDeviceInstance.setMaximumSize(QtCore.QSize(400, 16777215))
        self.cboDeviceInstance.setObjectName("cboDeviceInstance")
        self.verticalLayout_15.addWidget(self.cboDeviceInstance)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem1)
        self.tabSteps.addWidget(self.pgStepDeviceInstance)
        self.pgStepActionType = QtWidgets.QWidget()
        self.pgStepActionType.setObjectName("pgStepActionType")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pgStepActionType)
        self.verticalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblStepActionTitle = QtWidgets.QLabel(self.pgStepActionType)
        self.lblStepActionTitle.setWordWrap(True)
        self.lblStepActionTitle.setOpenExternalLinks(True)
        self.lblStepActionTitle.setObjectName("lblStepActionTitle")
        self.verticalLayout_5.addWidget(self.lblStepActionTitle)
        self.gbSeedSource = QtWidgets.QGroupBox(self.pgStepActionType)
        self.gbSeedSource.setTitle("")
        self.gbSeedSource.setFlat(False)
        self.gbSeedSource.setObjectName("gbSeedSource")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbSeedSource)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rbActRecoverWordsSafe = QtWidgets.QRadioButton(self.gbSeedSource)
        self.rbActRecoverWordsSafe.setChecked(True)
        self.rbActRecoverWordsSafe.setObjectName("rbActRecoverWordsSafe")
        self.verticalLayout_3.addWidget(self.rbActRecoverWordsSafe)
        self.rbActRecoverMnemonicWords = QtWidgets.QRadioButton(self.gbSeedSource)
        self.rbActRecoverMnemonicWords.setChecked(False)
        self.rbActRecoverMnemonicWords.setObjectName("rbActRecoverMnemonicWords")
        self.verticalLayout_3.addWidget(self.rbActRecoverMnemonicWords)
        self.rbActRecoverHexEntropy = QtWidgets.QRadioButton(self.gbSeedSource)
        self.rbActRecoverHexEntropy.setObjectName("rbActRecoverHexEntropy")
        self.verticalLayout_3.addWidget(self.rbActRecoverHexEntropy)
        self.rbActInitializeNewSeed = QtWidgets.QRadioButton(self.gbSeedSource)
        self.rbActInitializeNewSeed.setObjectName("rbActInitializeNewSeed")
        self.verticalLayout_3.addWidget(self.rbActInitializeNewSeed)
        self.rbActWipeDevice = QtWidgets.QRadioButton(self.gbSeedSource)
        self.rbActWipeDevice.setObjectName("rbActWipeDevice")
        self.verticalLayout_3.addWidget(self.rbActWipeDevice)
        self.verticalLayout_5.addWidget(self.gbSeedSource)
        self.lblActionTypeMessage = QtWidgets.QLabel(self.pgStepActionType)
        self.lblActionTypeMessage.setText("")
        self.lblActionTypeMessage.setWordWrap(True)
        self.lblActionTypeMessage.setObjectName("lblActionTypeMessage")
        self.verticalLayout_5.addWidget(self.lblActionTypeMessage)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.tabSteps.addWidget(self.pgStepActionType)
        self.pgStepWordCount = QtWidgets.QWidget()
        self.pgStepWordCount.setObjectName("pgStepWordCount")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pgStepWordCount)
        self.verticalLayout_6.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblStep1MnemonicWords = QtWidgets.QLabel(self.pgStepWordCount)
        self.lblStep1MnemonicWords.setWordWrap(True)
        self.lblStep1MnemonicWords.setObjectName("lblStep1MnemonicWords")
        self.verticalLayout_6.addWidget(self.lblStep1MnemonicWords)
        self.gbNumberOfMnemonicWords = QtWidgets.QGroupBox(self.pgStepWordCount)
        self.gbNumberOfMnemonicWords.setTitle("")
        self.gbNumberOfMnemonicWords.setObjectName("gbNumberOfMnemonicWords")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gbNumberOfMnemonicWords)
        self.verticalLayout_7.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_7.setSpacing(8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rbWordsCount24 = QtWidgets.QRadioButton(self.gbNumberOfMnemonicWords)
        self.rbWordsCount24.setChecked(True)
        self.rbWordsCount24.setObjectName("rbWordsCount24")
        self.verticalLayout_7.addWidget(self.rbWordsCount24)
        self.rbWordsCount18 = QtWidgets.QRadioButton(self.gbNumberOfMnemonicWords)
        self.rbWordsCount18.setObjectName("rbWordsCount18")
        self.verticalLayout_7.addWidget(self.rbWordsCount18)
        self.rbWordsCount12 = QtWidgets.QRadioButton(self.gbNumberOfMnemonicWords)
        self.rbWordsCount12.setObjectName("rbWordsCount12")
        self.verticalLayout_7.addWidget(self.rbWordsCount12)
        self.verticalLayout_6.addWidget(self.gbNumberOfMnemonicWords)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.tabSteps.addWidget(self.pgStepWordCount)
        self.pgSetpEntropy = QtWidgets.QWidget()
        self.pgSetpEntropy.setObjectName("pgSetpEntropy")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pgSetpEntropy)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblStep1HexEntropy = QtWidgets.QLabel(self.pgSetpEntropy)
        self.lblStep1HexEntropy.setObjectName("lblStep1HexEntropy")
        self.verticalLayout_4.addWidget(self.lblStep1HexEntropy)
        self.edtHexEntropy = QtWidgets.QLineEdit(self.pgSetpEntropy)
        self.edtHexEntropy.setObjectName("edtHexEntropy")
        self.verticalLayout_4.addWidget(self.edtHexEntropy)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.tabSteps.addWidget(self.pgSetpEntropy)
        self.pgStepWordList = QtWidgets.QWidget()
        self.pgStepWordList.setObjectName("pgStepWordList")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pgStepWordList)
        self.verticalLayout_8.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lblStepWordListTitle = QtWidgets.QLabel(self.pgStepWordList)
        self.lblStepWordListTitle.setWordWrap(True)
        self.lblStepWordListTitle.setOpenExternalLinks(True)
        self.lblStepWordListTitle.setObjectName("lblStepWordListTitle")
        self.verticalLayout_8.addWidget(self.lblStepWordListTitle)
        self.viewMnemonic = QtWidgets.QTableView(self.pgStepWordList)
        self.viewMnemonic.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.viewMnemonic.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.viewMnemonic.setObjectName("viewMnemonic")
        self.viewMnemonic.horizontalHeader().setVisible(False)
        self.viewMnemonic.horizontalHeader().setStretchLastSection(True)
        self.viewMnemonic.verticalHeader().setVisible(False)
        self.verticalLayout_8.addWidget(self.viewMnemonic)
        self.lblStepWordListMessage2 = QtWidgets.QLabel(self.pgStepWordList)
        self.lblStepWordListMessage2.setWordWrap(True)
        self.lblStepWordListMessage2.setObjectName("lblStepWordListMessage2")
        self.verticalLayout_8.addWidget(self.lblStepWordListMessage2)
        self.tabSteps.addWidget(self.pgStepWordList)
        self.pgStepInitOptions = QtWidgets.QWidget()
        self.pgStepInitOptions.setObjectName("pgStepInitOptions")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pgStepInitOptions)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblHwOptionsTitle = QtWidgets.QLabel(self.pgStepInitOptions)
        self.lblHwOptionsTitle.setWordWrap(True)
        self.lblHwOptionsTitle.setObjectName("lblHwOptionsTitle")
        self.verticalLayout_2.addWidget(self.lblHwOptionsTitle)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblHwOptionsDeviceLabel = QtWidgets.QLabel(self.pgStepInitOptions)
        self.lblHwOptionsDeviceLabel.setObjectName("lblHwOptionsDeviceLabel")
        self.gridLayout.addWidget(self.lblHwOptionsDeviceLabel, 0, 0, 1, 1)
        self.edtHwOptionsDeviceLabel = QtWidgets.QLineEdit(self.pgStepInitOptions)
        self.edtHwOptionsDeviceLabel.setPlaceholderText("")
        self.edtHwOptionsDeviceLabel.setObjectName("edtHwOptionsDeviceLabel")
        self.gridLayout.addWidget(self.edtHwOptionsDeviceLabel, 0, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.chbHwOptionsUsePassphrase = QtWidgets.QCheckBox(self.pgStepInitOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbHwOptionsUsePassphrase.sizePolicy().hasHeightForWidth())
        self.chbHwOptionsUsePassphrase.setSizePolicy(sizePolicy)
        self.chbHwOptionsUsePassphrase.setObjectName("chbHwOptionsUsePassphrase")
        self.horizontalLayout_7.addWidget(self.chbHwOptionsUsePassphrase)
        self.lblHwOptionsPassphraseReadmeLink = QtWidgets.QLabel(self.pgStepInitOptions)
        self.lblHwOptionsPassphraseReadmeLink.setTextFormat(QtCore.Qt.AutoText)
        self.lblHwOptionsPassphraseReadmeLink.setOpenExternalLinks(True)
        self.lblHwOptionsPassphraseReadmeLink.setObjectName("lblHwOptionsPassphraseReadmeLink")
        self.horizontalLayout_7.addWidget(self.lblHwOptionsPassphraseReadmeLink)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.wdgHwOptionsLedger = QtWidgets.QWidget(self.pgStepInitOptions)
        self.wdgHwOptionsLedger.setMinimumSize(QtCore.QSize(0, 0))
        self.wdgHwOptionsLedger.setObjectName("wdgHwOptionsLedger")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.wdgHwOptionsLedger)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.edtHwOptionsLedgerPassphrase = QtWidgets.QLineEdit(self.wdgHwOptionsLedger)
        self.edtHwOptionsLedgerPassphrase.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edtHwOptionsLedgerPassphrase.setObjectName("edtHwOptionsLedgerPassphrase")
        self.horizontalLayout_5.addWidget(self.edtHwOptionsLedgerPassphrase)
        self.btnShowPassphrase = QtWidgets.QToolButton(self.wdgHwOptionsLedger)
        self.btnShowPassphrase.setMinimumSize(QtCore.QSize(21, 21))
        self.btnShowPassphrase.setMaximumSize(QtCore.QSize(21, 21))
        self.btnShowPassphrase.setText("")
        self.btnShowPassphrase.setObjectName("btnShowPassphrase")
        self.horizontalLayout_5.addWidget(self.btnShowPassphrase)
        self.edtHwOptionsLedgerSecondaryPIN = QtWidgets.QLineEdit(self.wdgHwOptionsLedger)
        self.edtHwOptionsLedgerSecondaryPIN.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edtHwOptionsLedgerSecondaryPIN.setObjectName("edtHwOptionsLedgerSecondaryPIN")
        self.horizontalLayout_5.addWidget(self.edtHwOptionsLedgerSecondaryPIN)
        self.btnShowSecondaryPIN = QtWidgets.QToolButton(self.wdgHwOptionsLedger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShowSecondaryPIN.sizePolicy().hasHeightForWidth())
        self.btnShowSecondaryPIN.setSizePolicy(sizePolicy)
        self.btnShowSecondaryPIN.setMinimumSize(QtCore.QSize(21, 21))
        self.btnShowSecondaryPIN.setMaximumSize(QtCore.QSize(21, 21))
        self.btnShowSecondaryPIN.setText("")
        self.btnShowSecondaryPIN.setObjectName("btnShowSecondaryPIN")
        self.horizontalLayout_5.addWidget(self.btnShowSecondaryPIN)
        self.horizontalLayout_5.setStretch(0, 1)
        self.gridLayout.addWidget(self.wdgHwOptionsLedger, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edtHwOptionsPIN = QtWidgets.QLineEdit(self.pgStepInitOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHwOptionsPIN.sizePolicy().hasHeightForWidth())
        self.edtHwOptionsPIN.setSizePolicy(sizePolicy)
        self.edtHwOptionsPIN.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.edtHwOptionsPIN.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edtHwOptionsPIN.setObjectName("edtHwOptionsPIN")
        self.horizontalLayout_2.addWidget(self.edtHwOptionsPIN)
        self.btnShowPIN = QtWidgets.QToolButton(self.pgStepInitOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShowPIN.sizePolicy().hasHeightForWidth())
        self.btnShowPIN.setSizePolicy(sizePolicy)
        self.btnShowPIN.setMinimumSize(QtCore.QSize(21, 21))
        self.btnShowPIN.setMaximumSize(QtCore.QSize(21, 21))
        self.btnShowPIN.setText("")
        self.btnShowPIN.setObjectName("btnShowPIN")
        self.horizontalLayout_2.addWidget(self.btnShowPIN)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chbHwOptionsUsePIN = QtWidgets.QCheckBox(self.pgStepInitOptions)
        self.chbHwOptionsUsePIN.setChecked(True)
        self.chbHwOptionsUsePIN.setObjectName("chbHwOptionsUsePIN")
        self.horizontalLayout_3.addWidget(self.chbHwOptionsUsePIN)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.btnHwOptionsDetails = QtWidgets.QPushButton(self.pgStepInitOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHwOptionsDetails.sizePolicy().hasHeightForWidth())
        self.btnHwOptionsDetails.setSizePolicy(sizePolicy)
        self.btnHwOptionsDetails.setAutoDefault(False)
        self.btnHwOptionsDetails.setObjectName("btnHwOptionsDetails")
        self.verticalLayout_2.addWidget(self.btnHwOptionsDetails)
        self.fraDetails = QtWidgets.QFrame(self.pgStepInitOptions)
        self.fraDetails.setStyleSheet("")
        self.fraDetails.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraDetails.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fraDetails.setLineWidth(1)
        self.fraDetails.setObjectName("fraDetails")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.fraDetails)
        self.verticalLayout_11.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.wdgHwOptionsDetails = QtWidgets.QWidget(self.fraDetails)
        self.wdgHwOptionsDetails.setObjectName("wdgHwOptionsDetails")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.wdgHwOptionsDetails)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.edtHwOptionsPassphrase = QtWidgets.QLineEdit(self.wdgHwOptionsDetails)
        self.edtHwOptionsPassphrase.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtHwOptionsPassphrase.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edtHwOptionsPassphrase.setObjectName("edtHwOptionsPassphrase")
        self.gridLayout_2.addWidget(self.edtHwOptionsPassphrase, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.wdgHwOptionsDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(110, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.wdgHwOptionsDetails)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.btnRefreshAddressesPreview = QtWidgets.QPushButton(self.wdgHwOptionsDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRefreshAddressesPreview.sizePolicy().hasHeightForWidth())
        self.btnRefreshAddressesPreview.setSizePolicy(sizePolicy)
        self.btnRefreshAddressesPreview.setAutoDefault(False)
        self.btnRefreshAddressesPreview.setObjectName("btnRefreshAddressesPreview")
        self.gridLayout_2.addWidget(self.btnRefreshAddressesPreview, 1, 2, 1, 1)
        self.edtHwOptionsBip32Path = QtWidgets.QLineEdit(self.wdgHwOptionsDetails)
        self.edtHwOptionsBip32Path.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtHwOptionsBip32Path.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.edtHwOptionsBip32Path.setObjectName("edtHwOptionsBip32Path")
        self.gridLayout_2.addWidget(self.edtHwOptionsBip32Path, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_2)
        self.label_5 = QtWidgets.QLabel(self.wdgHwOptionsDetails)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.viewAddresses = QtWidgets.QTableView(self.wdgHwOptionsDetails)
        self.viewAddresses.setObjectName("viewAddresses")
        self.viewAddresses.horizontalHeader().setVisible(False)
        self.viewAddresses.horizontalHeader().setStretchLastSection(True)
        self.viewAddresses.verticalHeader().setVisible(False)
        self.viewAddresses.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_9.addWidget(self.viewAddresses)
        self.lblHwOptionsMessage1 = QtWidgets.QLabel(self.wdgHwOptionsDetails)
        self.lblHwOptionsMessage1.setStyleSheet("font-size:11px")
        self.lblHwOptionsMessage1.setWordWrap(True)
        self.lblHwOptionsMessage1.setOpenExternalLinks(True)
        self.lblHwOptionsMessage1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lblHwOptionsMessage1.setObjectName("lblHwOptionsMessage1")
        self.verticalLayout_9.addWidget(self.lblHwOptionsMessage1)
        self.verticalLayout_11.addWidget(self.wdgHwOptionsDetails)
        self.verticalLayout_2.addWidget(self.fraDetails)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.tabSteps.addWidget(self.pgStepInitOptions)
        self.pgStepSummary = QtWidgets.QWidget()
        self.pgStepSummary.setObjectName("pgStepSummary")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pgStepSummary)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lblStep5Tile = QtWidgets.QLabel(self.pgStepSummary)
        self.lblStep5Tile.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.lblStep5Tile.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStep5Tile.setObjectName("lblStep5Tile")
        self.verticalLayout_10.addWidget(self.lblStep5Tile)
        self.tabSteps.addWidget(self.pgStepSummary)
        self.verticalLayout.addWidget(self.tabSteps)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(6, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(HwInitializeDlg)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.widget = QtWidgets.QWidget(HwInitializeDlg)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(self.widget)
        self.btnCancel.setAutoDefault(False)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.btnBack = QtWidgets.QPushButton(self.widget)
        self.btnBack.setAutoDefault(False)
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout.addWidget(self.btnBack)
        self.btnNext = QtWidgets.QPushButton(self.widget)
        self.btnNext.setAutoDefault(False)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout.addWidget(self.btnNext)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(HwInitializeDlg)
        self.tabSteps.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HwInitializeDlg)

    def retranslateUi(self, HwInitializeDlg):
        _translate = QtCore.QCoreApplication.translate
        HwInitializeDlg.setWindowTitle(_translate("HwInitializeDlg", "Dialog"))
        self.lblStepDeviceType.setText(_translate("HwInitializeDlg", "<b>Select device type</b>\n"
""))
        self.rbDeviceTrezor.setText(_translate("HwInitializeDlg", "Trezor"))
        self.rbDeviceKeepkey.setText(_translate("HwInitializeDlg", "KeepKey"))
        self.rbDeviceLedger.setText(_translate("HwInitializeDlg", "Ledger Nano S"))
        self.lblStepDeviceInstanceMessage.setText(_translate("HwInitializeDlg", "<b>Select which device you want to use</b>"))
        self.lblStepActionTitle.setText(_translate("HwInitializeDlg", "<b>Select the action to perform</b>"))
        self.rbActRecoverWordsSafe.setText(_translate("HwInitializeDlg", "Recover hardware wallet from seed words - safe"))
        self.rbActRecoverMnemonicWords.setText(_translate("HwInitializeDlg", "Recover hardware wallet from seed words - convenient"))
        self.rbActRecoverHexEntropy.setText(_translate("HwInitializeDlg", "Recover hardware wallet from hexadecimal entropy"))
        self.rbActInitializeNewSeed.setText(_translate("HwInitializeDlg", "Initialize hardware wallet with newly generated seed words"))
        self.rbActWipeDevice.setText(_translate("HwInitializeDlg", "Wipe hardware wallet"))
        self.lblStep1MnemonicWords.setText(_translate("HwInitializeDlg", "<b>Number of words in your recovery seed</b>"))
        self.rbWordsCount24.setText(_translate("HwInitializeDlg", "24"))
        self.rbWordsCount18.setText(_translate("HwInitializeDlg", "18"))
        self.rbWordsCount12.setText(_translate("HwInitializeDlg", "12"))
        self.lblStep1HexEntropy.setText(_translate("HwInitializeDlg", "<b>Enter your recovery seed hexadecimal entropy</b>"))
        self.edtHexEntropy.setPlaceholderText(_translate("HwInitializeDlg", "32/24/16-byte hexadecimal string"))
        self.lblStepWordListTitle.setText(_translate("HwInitializeDlg", "<b>Enter the words of your recovery seed</b>"))
        self.lblStepWordListMessage2.setText(_translate("HwInitializeDlg", "You can copy and paste the complete set of seed words into this dialog directly (separated by spaces, commas or line breaks)."))
        self.lblHwOptionsTitle.setText(_translate("HwInitializeDlg", "<b>Set your hardware wallet initialization options</b>"))
        self.lblHwOptionsDeviceLabel.setText(_translate("HwInitializeDlg", "Device label:"))
        self.chbHwOptionsUsePassphrase.setWhatsThis(_translate("HwInitializeDlg", "<html><head/><body><p>Check the link attached &lt;a href=&quot;dash.org&quot;&gt;dash.org&lt;/a&gt;</p></body></html>"))
        self.chbHwOptionsUsePassphrase.setText(_translate("HwInitializeDlg", "Use passphrase"))
        self.lblHwOptionsPassphraseReadmeLink.setText(_translate("HwInitializeDlg", "(<a href=\"https://doc.satoshilabs.com/trezor-user/advanced_settings.html#using-passphrase-encrypted-seeds\">read this</a>)"))
        self.edtHwOptionsLedgerPassphrase.setToolTip(_translate("HwInitializeDlg", "<html><head/><body><p>This passphrase (if used) will be saved in your Ledger Nano S device and will be secured with the secondary PIN .</p></body></html>"))
        self.edtHwOptionsLedgerPassphrase.setPlaceholderText(_translate("HwInitializeDlg", "Passphrase"))
        self.btnShowPassphrase.setToolTip(_translate("HwInitializeDlg", "Show passphrase"))
        self.edtHwOptionsLedgerSecondaryPIN.setToolTip(_translate("HwInitializeDlg", "<html><head/><body><p>This PIN will be used to activate passphrase saved in your Ledger Nano S.</p></body></html>"))
        self.edtHwOptionsLedgerSecondaryPIN.setPlaceholderText(_translate("HwInitializeDlg", "Secondary PIN"))
        self.btnShowSecondaryPIN.setToolTip(_translate("HwInitializeDlg", "Show secondary PIN"))
        self.edtHwOptionsPIN.setPlaceholderText(_translate("HwInitializeDlg", "PIN"))
        self.btnShowPIN.setToolTip(_translate("HwInitializeDlg", "Show PIN"))
        self.chbHwOptionsUsePIN.setText(_translate("HwInitializeDlg", "Use PIN"))
        self.btnHwOptionsDetails.setText(_translate("HwInitializeDlg", "Show preview"))
        self.label_3.setText(_translate("HwInitializeDlg", "BIP32 start path:"))
        self.label.setText(_translate("HwInitializeDlg", "Passphrase:"))
        self.btnRefreshAddressesPreview.setText(_translate("HwInitializeDlg", "Apply and reload addresses"))
        self.edtHwOptionsBip32Path.setText(_translate("HwInitializeDlg", "44\'/5\'/0\'/0/0"))
        self.label_5.setText(_translate("HwInitializeDlg", "Dash addresses which will be available in the device after finishing the process:"))
        self.lblHwOptionsMessage1.setText(_translate("HwInitializeDlg", "Entropy:"))
        self.lblStep5Tile.setText(_translate("HwInitializeDlg", "<b>Operation successfully finished.</b>"))
        self.label_2.setText(_translate("HwInitializeDlg", "<a href=\"https://github.com/Bertrand256/dash-masternode-tool/blob/master/doc/hw-initialization-recovery.md\">Read the documentation on GitHub</a>"))
        self.btnCancel.setText(_translate("HwInitializeDlg", "Cancel"))
        self.btnBack.setText(_translate("HwInitializeDlg", "Back"))
        self.btnNext.setText(_translate("HwInitializeDlg", "Continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HwInitializeDlg = QtWidgets.QDialog()
    ui = Ui_HwInitializeDlg()
    ui.setupUi(HwInitializeDlg)
    HwInitializeDlg.show()
    sys.exit(app.exec_())

