# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/blogin/Projects/dash-masternode-tool/src/ui/ui_masternode_details.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WdgMasternodeDetails(object):
    def setupUi(self, WdgMasternodeDetails):
        WdgMasternodeDetails.setObjectName("WdgMasternodeDetails")
        WdgMasternodeDetails.resize(741, 280)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WdgMasternodeDetails.sizePolicy().hasHeightForWidth())
        WdgMasternodeDetails.setSizePolicy(sizePolicy)
        WdgMasternodeDetails.setMinimumSize(QtCore.QSize(700, 0))
        WdgMasternodeDetails.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WdgMasternodeDetails)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(WdgMasternodeDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lblUserRole = QtWidgets.QLabel(self.widget_2)
        self.lblUserRole.setMinimumSize(QtCore.QSize(144, 0))
        self.lblUserRole.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblUserRole.setObjectName("lblUserRole")
        self.horizontalLayout_12.addWidget(self.lblUserRole)
        self.chbRoleOwner = QtWidgets.QCheckBox(self.widget_2)
        self.chbRoleOwner.setChecked(True)
        self.chbRoleOwner.setObjectName("chbRoleOwner")
        self.horizontalLayout_12.addWidget(self.chbRoleOwner)
        self.chbRoleOperator = QtWidgets.QCheckBox(self.widget_2)
        self.chbRoleOperator.setChecked(True)
        self.chbRoleOperator.setObjectName("chbRoleOperator")
        self.horizontalLayout_12.addWidget(self.chbRoleOperator)
        self.chbRoleVoting = QtWidgets.QCheckBox(self.widget_2)
        self.chbRoleVoting.setChecked(True)
        self.chbRoleVoting.setObjectName("chbRoleVoting")
        self.horizontalLayout_12.addWidget(self.chbRoleVoting)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblName = QtWidgets.QLabel(self.widget_2)
        self.lblName.setMinimumSize(QtCore.QSize(144, 0))
        self.lblName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblName.setObjectName("lblName")
        self.horizontalLayout_2.addWidget(self.lblName)
        self.edtName = QtWidgets.QLineEdit(self.widget_2)
        self.edtName.setObjectName("edtName")
        self.horizontalLayout_2.addWidget(self.edtName)
        self.lblTitle = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle.sizePolicy().hasHeightForWidth())
        self.lblTitle.setSizePolicy(sizePolicy)
        self.lblTitle.setStyleSheet("")
        self.lblTitle.setText("")
        self.lblTitle.setWordWrap(False)
        self.lblTitle.setObjectName("lblTitle")
        self.horizontalLayout_2.addWidget(self.lblTitle)
        self.lblAction = QtWidgets.QLabel(self.widget_2)
        self.lblAction.setText("")
        self.lblAction.setObjectName("lblAction")
        self.horizontalLayout_2.addWidget(self.lblAction)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblIP = QtWidgets.QLabel(self.widget_2)
        self.lblIP.setMinimumSize(QtCore.QSize(144, 0))
        self.lblIP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblIP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIP.setObjectName("lblIP")
        self.horizontalLayout_3.addWidget(self.lblIP)
        self.edtIP = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtIP.sizePolicy().hasHeightForWidth())
        self.edtIP.setSizePolicy(sizePolicy)
        self.edtIP.setMinimumSize(QtCore.QSize(170, 0))
        self.edtIP.setClearButtonEnabled(True)
        self.edtIP.setObjectName("edtIP")
        self.horizontalLayout_3.addWidget(self.edtIP)
        self.lblPort = QtWidgets.QLabel(self.widget_2)
        self.lblPort.setObjectName("lblPort")
        self.horizontalLayout_3.addWidget(self.lblPort)
        self.edtPort = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPort.sizePolicy().hasHeightForWidth())
        self.edtPort.setSizePolicy(sizePolicy)
        self.edtPort.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edtPort.setClearButtonEnabled(True)
        self.edtPort.setObjectName("edtPort")
        self.horizontalLayout_3.addWidget(self.edtPort)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblCollateral = QtWidgets.QLabel(self.widget_2)
        self.lblCollateral.setMinimumSize(QtCore.QSize(144, 0))
        self.lblCollateral.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCollateral.setObjectName("lblCollateral")
        self.horizontalLayout_5.addWidget(self.lblCollateral)
        self.btnLocateCollateral = QtWidgets.QToolButton(self.widget_2)
        self.btnLocateCollateral.setObjectName("btnLocateCollateral")
        self.horizontalLayout_5.addWidget(self.btnLocateCollateral)
        self.edtCollateralAddress = QtWidgets.QLineEdit(self.widget_2)
        self.edtCollateralAddress.setClearButtonEnabled(True)
        self.edtCollateralAddress.setObjectName("edtCollateralAddress")
        self.horizontalLayout_5.addWidget(self.edtCollateralAddress)
        self.btnBip32PathToAddress = QtWidgets.QToolButton(self.widget_2)
        self.btnBip32PathToAddress.setObjectName("btnBip32PathToAddress")
        self.horizontalLayout_5.addWidget(self.btnBip32PathToAddress)
        self.lblCollateralPath = QtWidgets.QLabel(self.widget_2)
        self.lblCollateralPath.setObjectName("lblCollateralPath")
        self.horizontalLayout_5.addWidget(self.lblCollateralPath)
        self.edtCollateralPath = QtWidgets.QLineEdit(self.widget_2)
        self.edtCollateralPath.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtCollateralPath.setClearButtonEnabled(True)
        self.edtCollateralPath.setObjectName("edtCollateralPath")
        self.horizontalLayout_5.addWidget(self.edtCollateralPath)
        self.btnShowCollateralPathAddress = QtWidgets.QToolButton(self.widget_2)
        self.btnShowCollateralPathAddress.setMaximumSize(QtCore.QSize(16777215, 21))
        self.btnShowCollateralPathAddress.setText("")
        self.btnShowCollateralPathAddress.setObjectName("btnShowCollateralPathAddress")
        self.horizontalLayout_5.addWidget(self.btnShowCollateralPathAddress)
        self.horizontalLayout_5.setStretch(2, 2)
        self.horizontalLayout_5.setStretch(5, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblCollateralTxHash = QtWidgets.QLabel(self.widget_2)
        self.lblCollateralTxHash.setMinimumSize(QtCore.QSize(144, 0))
        self.lblCollateralTxHash.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCollateralTxHash.setObjectName("lblCollateralTxHash")
        self.horizontalLayout_6.addWidget(self.lblCollateralTxHash)
        self.edtCollateralTxHash = QtWidgets.QLineEdit(self.widget_2)
        self.edtCollateralTxHash.setClearButtonEnabled(True)
        self.edtCollateralTxHash.setObjectName("edtCollateralTxHash")
        self.horizontalLayout_6.addWidget(self.edtCollateralTxHash)
        self.lblCollateralTxIndex = QtWidgets.QLabel(self.widget_2)
        self.lblCollateralTxIndex.setObjectName("lblCollateralTxIndex")
        self.horizontalLayout_6.addWidget(self.lblCollateralTxIndex)
        self.edtCollateralTxIndex = QtWidgets.QLineEdit(self.widget_2)
        self.edtCollateralTxIndex.setMaximumSize(QtCore.QSize(50, 16777215))
        self.edtCollateralTxIndex.setObjectName("edtCollateralTxIndex")
        self.horizontalLayout_6.addWidget(self.edtCollateralTxIndex)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lblDMNTxHash = QtWidgets.QLabel(self.widget_2)
        self.lblDMNTxHash.setMinimumSize(QtCore.QSize(144, 0))
        self.lblDMNTxHash.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDMNTxHash.setObjectName("lblDMNTxHash")
        self.horizontalLayout_10.addWidget(self.lblDMNTxHash)
        self.edtDMNTxHash = QtWidgets.QLineEdit(self.widget_2)
        self.edtDMNTxHash.setClearButtonEnabled(True)
        self.edtDMNTxHash.setObjectName("edtDMNTxHash")
        self.horizontalLayout_10.addWidget(self.edtDMNTxHash)
        self.btnCopyProtxHash = QtWidgets.QToolButton(self.widget_2)
        self.btnCopyProtxHash.setText("")
        self.btnCopyProtxHash.setObjectName("btnCopyProtxHash")
        self.horizontalLayout_10.addWidget(self.btnCopyProtxHash)
        self.btnFindDMNTxHash = QtWidgets.QToolButton(self.widget_2)
        self.btnFindDMNTxHash.setObjectName("btnFindDMNTxHash")
        self.horizontalLayout_10.addWidget(self.btnFindDMNTxHash)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblOwnerKey = QtWidgets.QLabel(self.widget_2)
        self.lblOwnerKey.setMinimumSize(QtCore.QSize(144, 0))
        self.lblOwnerKey.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOwnerKey.setObjectName("lblOwnerKey")
        self.horizontalLayout_7.addWidget(self.lblOwnerKey)
        self.edtOwnerKey = QtWidgets.QLineEdit(self.widget_2)
        self.edtOwnerKey.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edtOwnerKey.setClearButtonEnabled(True)
        self.edtOwnerKey.setObjectName("edtOwnerKey")
        self.horizontalLayout_7.addWidget(self.edtOwnerKey)
        self.btnCopyOwnerKey = QtWidgets.QToolButton(self.widget_2)
        self.btnCopyOwnerKey.setMaximumSize(QtCore.QSize(16777215, 21))
        self.btnCopyOwnerKey.setText("")
        self.btnCopyOwnerKey.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btnCopyOwnerKey.setObjectName("btnCopyOwnerKey")
        self.horizontalLayout_7.addWidget(self.btnCopyOwnerKey)
        self.btnShowOwnerPrivateKey = QtWidgets.QToolButton(self.widget_2)
        self.btnShowOwnerPrivateKey.setMaximumSize(QtCore.QSize(16777215, 21))
        self.btnShowOwnerPrivateKey.setText("")
        self.btnShowOwnerPrivateKey.setCheckable(True)
        self.btnShowOwnerPrivateKey.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btnShowOwnerPrivateKey.setObjectName("btnShowOwnerPrivateKey")
        self.horizontalLayout_7.addWidget(self.btnShowOwnerPrivateKey)
        self.btnGenerateOwnerPrivateKey = QtWidgets.QToolButton(self.widget_2)
        self.btnGenerateOwnerPrivateKey.setObjectName("btnGenerateOwnerPrivateKey")
        self.horizontalLayout_7.addWidget(self.btnGenerateOwnerPrivateKey)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblOperatorKey = QtWidgets.QLabel(self.widget_2)
        self.lblOperatorKey.setMinimumSize(QtCore.QSize(144, 0))
        self.lblOperatorKey.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOperatorKey.setObjectName("lblOperatorKey")
        self.horizontalLayout_8.addWidget(self.lblOperatorKey)
        self.edtOperatorKey = QtWidgets.QLineEdit(self.widget_2)
        self.edtOperatorKey.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edtOperatorKey.setClearButtonEnabled(True)
        self.edtOperatorKey.setObjectName("edtOperatorKey")
        self.horizontalLayout_8.addWidget(self.edtOperatorKey)
        self.btnCopyOperatorKey = QtWidgets.QToolButton(self.widget_2)
        self.btnCopyOperatorKey.setMaximumSize(QtCore.QSize(16777215, 21))
        self.btnCopyOperatorKey.setText("")
        self.btnCopyOperatorKey.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btnCopyOperatorKey.setObjectName("btnCopyOperatorKey")
        self.horizontalLayout_8.addWidget(self.btnCopyOperatorKey)
        self.btnShowOperatorPrivateKey = QtWidgets.QToolButton(self.widget_2)
        self.btnShowOperatorPrivateKey.setMaximumSize(QtCore.QSize(16777215, 21))
        self.btnShowOperatorPrivateKey.setText("")
        self.btnShowOperatorPrivateKey.setCheckable(True)
        self.btnShowOperatorPrivateKey.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btnShowOperatorPrivateKey.setObjectName("btnShowOperatorPrivateKey")
        self.horizontalLayout_8.addWidget(self.btnShowOperatorPrivateKey)
        self.btnGenerateOperatorPrivateKey = QtWidgets.QToolButton(self.widget_2)
        self.btnGenerateOperatorPrivateKey.setObjectName("btnGenerateOperatorPrivateKey")
        self.horizontalLayout_8.addWidget(self.btnGenerateOperatorPrivateKey)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblVotingKey = QtWidgets.QLabel(self.widget_2)
        self.lblVotingKey.setMinimumSize(QtCore.QSize(144, 0))
        self.lblVotingKey.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblVotingKey.setObjectName("lblVotingKey")
        self.horizontalLayout_9.addWidget(self.lblVotingKey)
        self.edtVotingKey = QtWidgets.QLineEdit(self.widget_2)
        self.edtVotingKey.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edtVotingKey.setClearButtonEnabled(True)
        self.edtVotingKey.setObjectName("edtVotingKey")
        self.horizontalLayout_9.addWidget(self.edtVotingKey)
        self.btnCopyVotingKey = QtWidgets.QToolButton(self.widget_2)
        self.btnCopyVotingKey.setMaximumSize(QtCore.QSize(16777215, 21))
        self.btnCopyVotingKey.setText("")
        self.btnCopyVotingKey.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btnCopyVotingKey.setObjectName("btnCopyVotingKey")
        self.horizontalLayout_9.addWidget(self.btnCopyVotingKey)
        self.btnShowVotingPrivateKey = QtWidgets.QToolButton(self.widget_2)
        self.btnShowVotingPrivateKey.setMaximumSize(QtCore.QSize(16777215, 21))
        self.btnShowVotingPrivateKey.setText("")
        self.btnShowVotingPrivateKey.setCheckable(True)
        self.btnShowVotingPrivateKey.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btnShowVotingPrivateKey.setObjectName("btnShowVotingPrivateKey")
        self.horizontalLayout_9.addWidget(self.btnShowVotingPrivateKey)
        self.btnGenerateVotingPrivateKey = QtWidgets.QToolButton(self.widget_2)
        self.btnGenerateVotingPrivateKey.setObjectName("btnGenerateVotingPrivateKey")
        self.horizontalLayout_9.addWidget(self.btnGenerateVotingPrivateKey)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addWidget(self.widget_2)

        self.retranslateUi(WdgMasternodeDetails)
        QtCore.QMetaObject.connectSlotsByName(WdgMasternodeDetails)
        WdgMasternodeDetails.setTabOrder(self.edtName, self.edtIP)
        WdgMasternodeDetails.setTabOrder(self.edtIP, self.edtPort)
        WdgMasternodeDetails.setTabOrder(self.edtPort, self.edtCollateralAddress)
        WdgMasternodeDetails.setTabOrder(self.edtCollateralAddress, self.edtCollateralPath)
        WdgMasternodeDetails.setTabOrder(self.edtCollateralPath, self.edtCollateralTxHash)
        WdgMasternodeDetails.setTabOrder(self.edtCollateralTxHash, self.edtCollateralTxIndex)
        WdgMasternodeDetails.setTabOrder(self.edtCollateralTxIndex, self.edtDMNTxHash)
        WdgMasternodeDetails.setTabOrder(self.edtDMNTxHash, self.edtOwnerKey)
        WdgMasternodeDetails.setTabOrder(self.edtOwnerKey, self.edtOperatorKey)
        WdgMasternodeDetails.setTabOrder(self.edtOperatorKey, self.edtVotingKey)
        WdgMasternodeDetails.setTabOrder(self.edtVotingKey, self.chbRoleOwner)
        WdgMasternodeDetails.setTabOrder(self.chbRoleOwner, self.chbRoleOperator)
        WdgMasternodeDetails.setTabOrder(self.chbRoleOperator, self.chbRoleVoting)

    def retranslateUi(self, WdgMasternodeDetails):
        _translate = QtCore.QCoreApplication.translate
        WdgMasternodeDetails.setWindowTitle(_translate("WdgMasternodeDetails", "Form"))
        self.lblUserRole.setText(_translate("WdgMasternodeDetails", "User role"))
        self.chbRoleOwner.setText(_translate("WdgMasternodeDetails", "Owner"))
        self.chbRoleOperator.setText(_translate("WdgMasternodeDetails", "Operator"))
        self.chbRoleVoting.setText(_translate("WdgMasternodeDetails", "Voting"))
        self.lblName.setText(_translate("WdgMasternodeDetails", "Name"))
        self.lblIP.setText(_translate("WdgMasternodeDetails", "IP"))
        self.lblPort.setText(_translate("WdgMasternodeDetails", "port"))
        self.lblCollateral.setText(_translate("WdgMasternodeDetails", "Collateral address"))
        self.btnLocateCollateral.setText(_translate("WdgMasternodeDetails", "Locate collateral"))
        self.btnBip32PathToAddress.setToolTip(_translate("WdgMasternodeDetails", "Convert BIP32 path to address"))
        self.btnBip32PathToAddress.setText(_translate("WdgMasternodeDetails", "<<"))
        self.lblCollateralPath.setText(_translate("WdgMasternodeDetails", "path"))
        self.btnShowCollateralPathAddress.setToolTip(_translate("WdgMasternodeDetails", "Show Dash address for the entered BIP32 path"))
        self.lblCollateralTxHash.setText(_translate("WdgMasternodeDetails", "Collateral TX hash"))
        self.lblCollateralTxIndex.setText(_translate("WdgMasternodeDetails", "index"))
        self.lblDMNTxHash.setText(_translate("WdgMasternodeDetails", "Protx hash"))
        self.btnCopyProtxHash.setToolTip(_translate("WdgMasternodeDetails", "Copy protx hash to clipboard"))
        self.btnFindDMNTxHash.setToolTip(_translate("WdgMasternodeDetails", "Find DMN TX hash based on the ip/port or collateral tx"))
        self.btnFindDMNTxHash.setText(_translate("WdgMasternodeDetails", "Find"))
        self.lblOwnerKey.setText(_translate("WdgMasternodeDetails", "Owner private key"))
        self.btnCopyOwnerKey.setToolTip(_translate("WdgMasternodeDetails", "Copy key to clipboard"))
        self.btnShowOwnerPrivateKey.setToolTip(_translate("WdgMasternodeDetails", "Show/hide private key"))
        self.btnGenerateOwnerPrivateKey.setText(_translate("WdgMasternodeDetails", "Generate new"))
        self.lblOperatorKey.setText(_translate("WdgMasternodeDetails", "Operator private key"))
        self.btnCopyOperatorKey.setToolTip(_translate("WdgMasternodeDetails", "Copy key to clipboard"))
        self.btnShowOperatorPrivateKey.setToolTip(_translate("WdgMasternodeDetails", "Show/hide private key"))
        self.btnGenerateOperatorPrivateKey.setText(_translate("WdgMasternodeDetails", "Generate new"))
        self.lblVotingKey.setText(_translate("WdgMasternodeDetails", "Voting private key"))
        self.btnCopyVotingKey.setToolTip(_translate("WdgMasternodeDetails", "Copy key to clipboard"))
        self.btnShowVotingPrivateKey.setToolTip(_translate("WdgMasternodeDetails", "Show/hide private key"))
        self.btnGenerateVotingPrivateKey.setText(_translate("WdgMasternodeDetails", "Generate new"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WdgMasternodeDetails = QtWidgets.QWidget()
    ui = Ui_WdgMasternodeDetails()
    ui.setupUi(WdgMasternodeDetails)
    WdgMasternodeDetails.show()
    sys.exit(app.exec_())

