# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/ui_reg_masternode_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegMasternodeDlg(object):
    def setupUi(self, RegMasternodeDlg):
        RegMasternodeDlg.setObjectName("RegMasternodeDlg")
        RegMasternodeDlg.resize(808, 659)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RegMasternodeDlg.sizePolicy().hasHeightForWidth())
        RegMasternodeDlg.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(RegMasternodeDlg)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(RegMasternodeDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page0.sizePolicy().hasHeightForWidth())
        self.page0.setSizePolicy(sizePolicy)
        self.page0.setObjectName("page0")
        self.gridLayout = QtWidgets.QGridLayout(self.page0)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.lblOwnerMsg = QtWidgets.QLabel(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOwnerMsg.sizePolicy().hasHeightForWidth())
        self.lblOwnerMsg.setSizePolicy(sizePolicy)
        self.lblOwnerMsg.setWordWrap(True)
        self.lblOwnerMsg.setOpenExternalLinks(True)
        self.lblOwnerMsg.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblOwnerMsg.setObjectName("lblOwnerMsg")
        self.gridLayout.addWidget(self.lblOwnerMsg, 14, 1, 1, 1)
        self.lblVotingMsg = QtWidgets.QLabel(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblVotingMsg.sizePolicy().hasHeightForWidth())
        self.lblVotingMsg.setSizePolicy(sizePolicy)
        self.lblVotingMsg.setWordWrap(True)
        self.lblVotingMsg.setOpenExternalLinks(True)
        self.lblVotingMsg.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblVotingMsg.setObjectName("lblVotingMsg")
        self.gridLayout.addWidget(self.lblVotingMsg, 21, 1, 1, 1)
        self.layIP = QtWidgets.QHBoxLayout()
        self.layIP.setSpacing(8)
        self.layIP.setObjectName("layIP")
        self.edtIP = QtWidgets.QLineEdit(self.page0)
        self.edtIP.setClearButtonEnabled(True)
        self.edtIP.setObjectName("edtIP")
        self.layIP.addWidget(self.edtIP)
        self.label_5 = QtWidgets.QLabel(self.page0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.layIP.addWidget(self.label_5)
        self.edtPort = QtWidgets.QLineEdit(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPort.sizePolicy().hasHeightForWidth())
        self.edtPort.setSizePolicy(sizePolicy)
        self.edtPort.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edtPort.setClearButtonEnabled(True)
        self.edtPort.setObjectName("edtPort")
        self.layIP.addWidget(self.edtPort)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layIP.addItem(spacerItem)
        self.gridLayout.addLayout(self.layIP, 3, 1, 1, 1)
        self.layOperatorReward = QtWidgets.QHBoxLayout()
        self.layOperatorReward.setSpacing(8)
        self.layOperatorReward.setObjectName("layOperatorReward")
        self.chbWholeMNReward = QtWidgets.QCheckBox(self.page0)
        self.chbWholeMNReward.setObjectName("chbWholeMNReward")
        self.layOperatorReward.addWidget(self.chbWholeMNReward)
        self.edtOperatorReward = QtWidgets.QDoubleSpinBox(self.page0)
        self.edtOperatorReward.setMaximum(100.0)
        self.edtOperatorReward.setObjectName("edtOperatorReward")
        self.layOperatorReward.addWidget(self.edtOperatorReward)
        self.label_16 = QtWidgets.QLabel(self.page0)
        self.label_16.setObjectName("label_16")
        self.layOperatorReward.addWidget(self.label_16)
        self.gridLayout.addLayout(self.layOperatorReward, 10, 1, 1, 1)
        self.layVotingKey = QtWidgets.QHBoxLayout()
        self.layVotingKey.setSpacing(8)
        self.layVotingKey.setObjectName("layVotingKey")
        self.edtVotingKey = QtWidgets.QLineEdit(self.page0)
        self.edtVotingKey.setClearButtonEnabled(True)
        self.edtVotingKey.setObjectName("edtVotingKey")
        self.layVotingKey.addWidget(self.edtVotingKey)
        self.btnGenerateVotingKey = QtWidgets.QToolButton(self.page0)
        self.btnGenerateVotingKey.setObjectName("btnGenerateVotingKey")
        self.layVotingKey.addWidget(self.btnGenerateVotingKey)
        self.gridLayout.addLayout(self.layVotingKey, 19, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.page0)
        self.line_5.setMinimumSize(QtCore.QSize(0, 12))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 15, 1, 1, 1)
        self.layOperatorKey = QtWidgets.QHBoxLayout()
        self.layOperatorKey.setSpacing(8)
        self.layOperatorKey.setObjectName("layOperatorKey")
        self.edtOperatorKey = QtWidgets.QLineEdit(self.page0)
        self.edtOperatorKey.setClearButtonEnabled(True)
        self.edtOperatorKey.setObjectName("edtOperatorKey")
        self.layOperatorKey.addWidget(self.edtOperatorKey)
        self.btnGenerateOperatorKey = QtWidgets.QToolButton(self.page0)
        self.btnGenerateOperatorKey.setObjectName("btnGenerateOperatorKey")
        self.layOperatorKey.addWidget(self.btnGenerateOperatorKey)
        self.gridLayout.addLayout(self.layOperatorKey, 16, 1, 1, 1)
        self.layPayoutAddress = QtWidgets.QHBoxLayout()
        self.layPayoutAddress.setSpacing(8)
        self.layPayoutAddress.setObjectName("layPayoutAddress")
        self.edtPayoutAddress = QtWidgets.QLineEdit(self.page0)
        self.edtPayoutAddress.setClearButtonEnabled(True)
        self.edtPayoutAddress.setObjectName("edtPayoutAddress")
        self.layPayoutAddress.addWidget(self.edtPayoutAddress)
        self.gridLayout.addLayout(self.layPayoutAddress, 7, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.page0)
        self.line_2.setMinimumSize(QtCore.QSize(0, 12))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 6, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.page0)
        self.line_3.setMinimumSize(QtCore.QSize(0, 12))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 9, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.page0)
        self.line.setMinimumSize(QtCore.QSize(0, 12))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.page0)
        self.line_6.setMinimumSize(QtCore.QSize(0, 12))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 18, 1, 1, 1)
        self.lblIPMsg = QtWidgets.QLabel(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblIPMsg.sizePolicy().hasHeightForWidth())
        self.lblIPMsg.setSizePolicy(sizePolicy)
        self.lblIPMsg.setMinimumSize(QtCore.QSize(0, 8))
        self.lblIPMsg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblIPMsg.setWordWrap(True)
        self.lblIPMsg.setOpenExternalLinks(True)
        self.lblIPMsg.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblIPMsg.setObjectName("lblIPMsg")
        self.gridLayout.addWidget(self.lblIPMsg, 5, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 10, 0, 1, 1)
        self.layCollateral = QtWidgets.QHBoxLayout()
        self.layCollateral.setSpacing(8)
        self.layCollateral.setObjectName("layCollateral")
        self.edtCollateralTx = QtWidgets.QLineEdit(self.page0)
        self.edtCollateralTx.setClearButtonEnabled(True)
        self.edtCollateralTx.setObjectName("edtCollateralTx")
        self.layCollateral.addWidget(self.edtCollateralTx)
        self.label_2 = QtWidgets.QLabel(self.page0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.layCollateral.addWidget(self.label_2)
        self.edtCollateralIndex = QtWidgets.QLineEdit(self.page0)
        self.edtCollateralIndex.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtCollateralIndex.setObjectName("edtCollateralIndex")
        self.layCollateral.addWidget(self.edtCollateralIndex)
        self.gridLayout.addLayout(self.layCollateral, 0, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.page0)
        self.line_4.setMinimumSize(QtCore.QSize(0, 12))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 12, 1, 1, 1)
        self.lblOperatorRewardMsg = QtWidgets.QLabel(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOperatorRewardMsg.sizePolicy().hasHeightForWidth())
        self.lblOperatorRewardMsg.setSizePolicy(sizePolicy)
        self.lblOperatorRewardMsg.setWordWrap(True)
        self.lblOperatorRewardMsg.setOpenExternalLinks(True)
        self.lblOperatorRewardMsg.setObjectName("lblOperatorRewardMsg")
        self.gridLayout.addWidget(self.lblOperatorRewardMsg, 11, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.page0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edtOwnerKey = QtWidgets.QLineEdit(self.page0)
        self.edtOwnerKey.setText("")
        self.edtOwnerKey.setClearButtonEnabled(True)
        self.edtOwnerKey.setObjectName("edtOwnerKey")
        self.horizontalLayout_3.addWidget(self.edtOwnerKey)
        self.btnGenerateOwnerKey = QtWidgets.QToolButton(self.page0)
        self.btnGenerateOwnerKey.setObjectName("btnGenerateOwnerKey")
        self.horizontalLayout_3.addWidget(self.btnGenerateOwnerKey)
        self.gridLayout.addLayout(self.horizontalLayout_3, 13, 1, 1, 1)
        self.lblCollateralTxMsg = QtWidgets.QLabel(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCollateralTxMsg.sizePolicy().hasHeightForWidth())
        self.lblCollateralTxMsg.setSizePolicy(sizePolicy)
        self.lblCollateralTxMsg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblCollateralTxMsg.setMidLineWidth(0)
        self.lblCollateralTxMsg.setWordWrap(True)
        self.lblCollateralTxMsg.setOpenExternalLinks(False)
        self.lblCollateralTxMsg.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblCollateralTxMsg.setObjectName("lblCollateralTxMsg")
        self.gridLayout.addWidget(self.lblCollateralTxMsg, 1, 1, 1, 1)
        self.lblPayoutMsg = QtWidgets.QLabel(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPayoutMsg.sizePolicy().hasHeightForWidth())
        self.lblPayoutMsg.setSizePolicy(sizePolicy)
        self.lblPayoutMsg.setWordWrap(True)
        self.lblPayoutMsg.setOpenExternalLinks(True)
        self.lblPayoutMsg.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblPayoutMsg.setObjectName("lblPayoutMsg")
        self.gridLayout.addWidget(self.lblPayoutMsg, 8, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lblOperatorMsg = QtWidgets.QLabel(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOperatorMsg.sizePolicy().hasHeightForWidth())
        self.lblOperatorMsg.setSizePolicy(sizePolicy)
        self.lblOperatorMsg.setWordWrap(True)
        self.lblOperatorMsg.setOpenExternalLinks(True)
        self.lblOperatorMsg.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblOperatorMsg.setObjectName("lblOperatorMsg")
        self.gridLayout.addWidget(self.lblOperatorMsg, 17, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 22, 1, 1, 1)
        self.lblOwnerKey = QtWidgets.QLabel(self.page0)
        self.lblOwnerKey.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOwnerKey.setObjectName("lblOwnerKey")
        self.gridLayout.addWidget(self.lblOwnerKey, 13, 0, 1, 1)
        self.lblOperatorKey = QtWidgets.QLabel(self.page0)
        self.lblOperatorKey.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOperatorKey.setObjectName("lblOperatorKey")
        self.gridLayout.addWidget(self.lblOperatorKey, 16, 0, 1, 1)
        self.lblVotingKey = QtWidgets.QLabel(self.page0)
        self.lblVotingKey.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblVotingKey.setObjectName("lblVotingKey")
        self.gridLayout.addWidget(self.lblVotingKey, 19, 0, 1, 1)
        self.stackedWidget.addWidget(self.page0)
        self.page1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page1.sizePolicy().hasHeightForWidth())
        self.page1.setSizePolicy(sizePolicy)
        self.page1.setObjectName("page1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.page1)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.gbDashNodeType = QtWidgets.QGroupBox(self.page1)
        self.gbDashNodeType.setTitle("")
        self.gbDashNodeType.setFlat(False)
        self.gbDashNodeType.setObjectName("gbDashNodeType")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbDashNodeType)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rbDMTDashNodeType = QtWidgets.QRadioButton(self.gbDashNodeType)
        self.rbDMTDashNodeType.setObjectName("rbDMTDashNodeType")
        self.verticalLayout_3.addWidget(self.rbDMTDashNodeType)
        self.rbOwnDashNodeType = QtWidgets.QRadioButton(self.gbDashNodeType)
        self.rbOwnDashNodeType.setObjectName("rbOwnDashNodeType")
        self.verticalLayout_3.addWidget(self.rbOwnDashNodeType)
        self.verticalLayout_2.addWidget(self.gbDashNodeType)
        self.lblDashNodeTypeMessage = QtWidgets.QLabel(self.page1)
        self.lblDashNodeTypeMessage.setText("")
        self.lblDashNodeTypeMessage.setWordWrap(True)
        self.lblDashNodeTypeMessage.setOpenExternalLinks(True)
        self.lblDashNodeTypeMessage.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblDashNodeTypeMessage.setObjectName("lblDashNodeTypeMessage")
        self.verticalLayout_2.addWidget(self.lblDashNodeTypeMessage)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page2.sizePolicy().hasHeightForWidth())
        self.page2.setSizePolicy(sizePolicy)
        self.page2.setObjectName("page2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblProtxTransaction1 = QtWidgets.QLabel(self.page2)
        self.lblProtxTransaction1.setWordWrap(True)
        self.lblProtxTransaction1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblProtxTransaction1.setObjectName("lblProtxTransaction1")
        self.verticalLayout_4.addWidget(self.lblProtxTransaction1)
        self.lblProtxTransaction2 = QtWidgets.QLabel(self.page2)
        self.lblProtxTransaction2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblProtxTransaction2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblProtxTransaction2.setWordWrap(True)
        self.lblProtxTransaction2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblProtxTransaction2.setObjectName("lblProtxTransaction2")
        self.verticalLayout_4.addWidget(self.lblProtxTransaction2)
        self.lblProtxTransaction3 = QtWidgets.QLabel(self.page2)
        self.lblProtxTransaction3.setWordWrap(True)
        self.lblProtxTransaction3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblProtxTransaction3.setObjectName("lblProtxTransaction3")
        self.verticalLayout_4.addWidget(self.lblProtxTransaction3)
        self.lblProtxTransaction4 = QtWidgets.QLabel(self.page2)
        self.lblProtxTransaction4.setWordWrap(True)
        self.lblProtxTransaction4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblProtxTransaction4.setObjectName("lblProtxTransaction4")
        self.verticalLayout_4.addWidget(self.lblProtxTransaction4)
        self.label_6 = QtWidgets.QLabel(self.page2)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page3.sizePolicy().hasHeightForWidth())
        self.page3.setSizePolicy(sizePolicy)
        self.page3.setObjectName("page3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page3)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.page3)
        self.label_10.setWordWrap(True)
        self.label_10.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.page3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.edtManualFundingAddress = QtWidgets.QLineEdit(self.page3)
        self.edtManualFundingAddress.setObjectName("edtManualFundingAddress")
        self.horizontalLayout_4.addWidget(self.edtManualFundingAddress)
        self.btnManualFundingAddressPaste = QtWidgets.QToolButton(self.page3)
        self.btnManualFundingAddressPaste.setText("")
        self.btnManualFundingAddressPaste.setObjectName("btnManualFundingAddressPaste")
        self.horizontalLayout_4.addWidget(self.btnManualFundingAddressPaste)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.label_13 = QtWidgets.QLabel(self.page3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.layManualStep1 = QtWidgets.QHBoxLayout()
        self.layManualStep1.setObjectName("layManualStep1")
        self.edtManualProtxPrepare = QtWidgets.QPlainTextEdit(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtManualProtxPrepare.sizePolicy().hasHeightForWidth())
        self.edtManualProtxPrepare.setSizePolicy(sizePolicy)
        self.edtManualProtxPrepare.setTabChangesFocus(True)
        self.edtManualProtxPrepare.setReadOnly(True)
        self.edtManualProtxPrepare.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.edtManualProtxPrepare.setObjectName("edtManualProtxPrepare")
        self.layManualStep1.addWidget(self.edtManualProtxPrepare)
        self.btnManualProtxPrepareCopy = QtWidgets.QToolButton(self.page3)
        self.btnManualProtxPrepareCopy.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnManualProtxPrepareCopy.setText("")
        self.btnManualProtxPrepareCopy.setObjectName("btnManualProtxPrepareCopy")
        self.layManualStep1.addWidget(self.btnManualProtxPrepareCopy)
        self.verticalLayout_5.addLayout(self.layManualStep1)
        self.label_14 = QtWidgets.QLabel(self.page3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.layManualStep2 = QtWidgets.QHBoxLayout()
        self.layManualStep2.setObjectName("layManualStep2")
        self.edtManualProtxPrepareResult = QtWidgets.QPlainTextEdit(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtManualProtxPrepareResult.sizePolicy().hasHeightForWidth())
        self.edtManualProtxPrepareResult.setSizePolicy(sizePolicy)
        self.edtManualProtxPrepareResult.setTabChangesFocus(True)
        self.edtManualProtxPrepareResult.setObjectName("edtManualProtxPrepareResult")
        self.layManualStep2.addWidget(self.edtManualProtxPrepareResult)
        self.btnManualProtxPrepareResultPaste = QtWidgets.QToolButton(self.page3)
        self.btnManualProtxPrepareResultPaste.setText("")
        self.btnManualProtxPrepareResultPaste.setObjectName("btnManualProtxPrepareResultPaste")
        self.layManualStep2.addWidget(self.btnManualProtxPrepareResultPaste)
        self.verticalLayout_5.addLayout(self.layManualStep2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnManualSignProtx = QtWidgets.QPushButton(self.page3)
        self.btnManualSignProtx.setAutoDefault(False)
        self.btnManualSignProtx.setObjectName("btnManualSignProtx")
        self.horizontalLayout_2.addWidget(self.btnManualSignProtx)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.label_17 = QtWidgets.QLabel(self.page3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.layManualStep3 = QtWidgets.QHBoxLayout()
        self.layManualStep3.setObjectName("layManualStep3")
        self.edtManualProtxSubmit = QtWidgets.QPlainTextEdit(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtManualProtxSubmit.sizePolicy().hasHeightForWidth())
        self.edtManualProtxSubmit.setSizePolicy(sizePolicy)
        self.edtManualProtxSubmit.setTabChangesFocus(True)
        self.edtManualProtxSubmit.setReadOnly(True)
        self.edtManualProtxSubmit.setObjectName("edtManualProtxSubmit")
        self.layManualStep3.addWidget(self.edtManualProtxSubmit)
        self.btnManualProtxSubmitCopy = QtWidgets.QToolButton(self.page3)
        self.btnManualProtxSubmitCopy.setText("")
        self.btnManualProtxSubmitCopy.setObjectName("btnManualProtxSubmitCopy")
        self.layManualStep3.addWidget(self.btnManualProtxSubmitCopy)
        self.verticalLayout_5.addLayout(self.layManualStep3)
        self.label_11 = QtWidgets.QLabel(self.page3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.layManualStep4 = QtWidgets.QHBoxLayout()
        self.layManualStep4.setObjectName("layManualStep4")
        self.edtManualTxHash = QtWidgets.QLineEdit(self.page3)
        self.edtManualTxHash.setObjectName("edtManualTxHash")
        self.layManualStep4.addWidget(self.edtManualTxHash)
        self.btnManualTxHashPaste = QtWidgets.QToolButton(self.page3)
        self.btnManualTxHashPaste.setText("")
        self.btnManualTxHashPaste.setObjectName("btnManualTxHashPaste")
        self.layManualStep4.addWidget(self.btnManualTxHashPaste)
        self.verticalLayout_5.addLayout(self.layManualStep4)
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page4.sizePolicy().hasHeightForWidth())
        self.page4.setSizePolicy(sizePolicy)
        self.page4.setObjectName("page4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblProtxSummary1 = QtWidgets.QLabel(self.page4)
        self.lblProtxSummary1.setWordWrap(True)
        self.lblProtxSummary1.setObjectName("lblProtxSummary1")
        self.verticalLayout_6.addWidget(self.lblProtxSummary1)
        self.lblProtxSummary2 = QtWidgets.QLabel(self.page4)
        self.lblProtxSummary2.setWordWrap(True)
        self.lblProtxSummary2.setObjectName("lblProtxSummary2")
        self.verticalLayout_6.addWidget(self.lblProtxSummary2)
        self.edtProtxSummary = QtWidgets.QTextBrowser(self.page4)
        self.edtProtxSummary.setObjectName("edtProtxSummary")
        self.verticalLayout_6.addWidget(self.edtProtxSummary)
        self.lblProtxSummary3 = QtWidgets.QLabel(self.page4)
        self.lblProtxSummary3.setWordWrap(True)
        self.lblProtxSummary3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblProtxSummary3.setObjectName("lblProtxSummary3")
        self.verticalLayout_6.addWidget(self.lblProtxSummary3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.edtSummaryDMNOperatorKey = QtWidgets.QLineEdit(self.page4)
        self.edtSummaryDMNOperatorKey.setReadOnly(True)
        self.edtSummaryDMNOperatorKey.setObjectName("edtSummaryDMNOperatorKey")
        self.horizontalLayout_5.addWidget(self.edtSummaryDMNOperatorKey)
        self.btnSummaryDMNOperatorKeyCopy = QtWidgets.QToolButton(self.page4)
        self.btnSummaryDMNOperatorKeyCopy.setText("")
        self.btnSummaryDMNOperatorKeyCopy.setObjectName("btnSummaryDMNOperatorKeyCopy")
        self.horizontalLayout_5.addWidget(self.btnSummaryDMNOperatorKeyCopy)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.page4)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.frame = QtWidgets.QFrame(RegMasternodeDlg)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(self.frame)
        self.btnCancel.setAutoDefault(False)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.lblFieldHints = QtWidgets.QLabel(self.frame)
        self.lblFieldHints.setObjectName("lblFieldHints")
        self.horizontalLayout.addWidget(self.lblFieldHints)
        self.lblDocumentation = QtWidgets.QLabel(self.frame)
        self.lblDocumentation.setText("")
        self.lblDocumentation.setOpenExternalLinks(True)
        self.lblDocumentation.setObjectName("lblDocumentation")
        self.horizontalLayout.addWidget(self.lblDocumentation)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btnBack = QtWidgets.QPushButton(self.frame)
        self.btnBack.setAutoDefault(False)
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout.addWidget(self.btnBack)
        self.btnContinue = QtWidgets.QPushButton(self.frame)
        self.btnContinue.setAutoDefault(False)
        self.btnContinue.setObjectName("btnContinue")
        self.horizontalLayout.addWidget(self.btnContinue)
        self.btnClose = QtWidgets.QPushButton(self.frame)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(RegMasternodeDlg)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RegMasternodeDlg)
        RegMasternodeDlg.setTabOrder(self.edtCollateralTx, self.edtCollateralIndex)
        RegMasternodeDlg.setTabOrder(self.edtCollateralIndex, self.edtIP)
        RegMasternodeDlg.setTabOrder(self.edtIP, self.edtPort)
        RegMasternodeDlg.setTabOrder(self.edtPort, self.edtPayoutAddress)
        RegMasternodeDlg.setTabOrder(self.edtPayoutAddress, self.chbWholeMNReward)
        RegMasternodeDlg.setTabOrder(self.chbWholeMNReward, self.edtOperatorReward)
        RegMasternodeDlg.setTabOrder(self.edtOperatorReward, self.edtOwnerKey)
        RegMasternodeDlg.setTabOrder(self.edtOwnerKey, self.btnGenerateOwnerKey)
        RegMasternodeDlg.setTabOrder(self.btnGenerateOwnerKey, self.edtOperatorKey)
        RegMasternodeDlg.setTabOrder(self.edtOperatorKey, self.btnGenerateOperatorKey)
        RegMasternodeDlg.setTabOrder(self.btnGenerateOperatorKey, self.edtVotingKey)
        RegMasternodeDlg.setTabOrder(self.edtVotingKey, self.btnGenerateVotingKey)
        RegMasternodeDlg.setTabOrder(self.btnGenerateVotingKey, self.btnContinue)
        RegMasternodeDlg.setTabOrder(self.btnContinue, self.edtManualProtxPrepareResult)
        RegMasternodeDlg.setTabOrder(self.edtManualProtxPrepareResult, self.btnManualSignProtx)
        RegMasternodeDlg.setTabOrder(self.btnManualSignProtx, self.edtManualProtxSubmit)
        RegMasternodeDlg.setTabOrder(self.edtManualProtxSubmit, self.edtProtxSummary)
        RegMasternodeDlg.setTabOrder(self.edtProtxSummary, self.edtManualFundingAddress)
        RegMasternodeDlg.setTabOrder(self.edtManualFundingAddress, self.btnClose)
        RegMasternodeDlg.setTabOrder(self.btnClose, self.rbOwnDashNodeType)
        RegMasternodeDlg.setTabOrder(self.rbOwnDashNodeType, self.btnManualProtxPrepareResultPaste)
        RegMasternodeDlg.setTabOrder(self.btnManualProtxPrepareResultPaste, self.btnBack)
        RegMasternodeDlg.setTabOrder(self.btnBack, self.btnManualProtxSubmitCopy)
        RegMasternodeDlg.setTabOrder(self.btnManualProtxSubmitCopy, self.edtManualProtxPrepare)
        RegMasternodeDlg.setTabOrder(self.edtManualProtxPrepare, self.btnManualTxHashPaste)
        RegMasternodeDlg.setTabOrder(self.btnManualTxHashPaste, self.btnCancel)
        RegMasternodeDlg.setTabOrder(self.btnCancel, self.btnManualFundingAddressPaste)
        RegMasternodeDlg.setTabOrder(self.btnManualFundingAddressPaste, self.edtSummaryDMNOperatorKey)
        RegMasternodeDlg.setTabOrder(self.edtSummaryDMNOperatorKey, self.btnSummaryDMNOperatorKeyCopy)
        RegMasternodeDlg.setTabOrder(self.btnSummaryDMNOperatorKeyCopy, self.edtManualTxHash)
        RegMasternodeDlg.setTabOrder(self.edtManualTxHash, self.rbDMTDashNodeType)

    def retranslateUi(self, RegMasternodeDlg):
        _translate = QtCore.QCoreApplication.translate
        RegMasternodeDlg.setWindowTitle(_translate("RegMasternodeDlg", "Masternode migration wizard"))
        self.lblOwnerMsg.setText(_translate("RegMasternodeDlg", "..."))
        self.lblVotingMsg.setText(_translate("RegMasternodeDlg", "..."))
        self.label_5.setText(_translate("RegMasternodeDlg", "Port"))
        self.chbWholeMNReward.setText(_translate("RegMasternodeDlg", "The entire Masternode reward goes to the owner"))
        self.label_16.setText(_translate("RegMasternodeDlg", "%"))
        self.btnGenerateVotingKey.setText(_translate("RegMasternodeDlg", "Generate new"))
        self.btnGenerateOperatorKey.setText(_translate("RegMasternodeDlg", "Generate new"))
        self.label_8.setText(_translate("RegMasternodeDlg", "Payout address"))
        self.lblIPMsg.setText(_translate("RegMasternodeDlg", "..."))
        self.label_15.setText(_translate("RegMasternodeDlg", "Operator reward"))
        self.label_2.setText(_translate("RegMasternodeDlg", "TX index"))
        self.lblOperatorRewardMsg.setText(_translate("RegMasternodeDlg", "..."))
        self.label.setText(_translate("RegMasternodeDlg", "Collateral TX"))
        self.btnGenerateOwnerKey.setText(_translate("RegMasternodeDlg", "Generate new"))
        self.lblCollateralTxMsg.setText(_translate("RegMasternodeDlg", "..."))
        self.lblPayoutMsg.setText(_translate("RegMasternodeDlg", "..."))
        self.label_3.setText(_translate("RegMasternodeDlg", "IP"))
        self.lblOperatorMsg.setText(_translate("RegMasternodeDlg", "..."))
        self.lblOwnerKey.setText(_translate("RegMasternodeDlg", "<b>Owner private key</b>"))
        self.lblOperatorKey.setText(_translate("RegMasternodeDlg", "<b>Operator private key</b> "))
        self.lblVotingKey.setText(_translate("RegMasternodeDlg", "<b>Voting private key</b>"))
        self.label_4.setText(_translate("RegMasternodeDlg", "<b>Choose the Firo wallet type to be used for submitting ProRegTx transaction.</b>"))
        self.rbDMTDashNodeType.setText(_translate("RegMasternodeDlg", "Remote Firo RPC Node (automatic method)"))
        self.rbOwnDashNodeType.setText(_translate("RegMasternodeDlg", "Your own Firo-Qt wallet (manual method)"))
        self.lblProtxTransaction1.setText(_translate("RegMasternodeDlg", "1."))
        self.lblProtxTransaction2.setText(_translate("RegMasternodeDlg", "message"))
        self.lblProtxTransaction3.setText(_translate("RegMasternodeDlg", "2."))
        self.lblProtxTransaction4.setText(_translate("RegMasternodeDlg", "3."))
        self.label_10.setText(_translate("RegMasternodeDlg", "<span style=\"color:red\"><b>Important:</b></span> A Firo Core wallet with sufficient funds to cover transaction fees is required to complete the steps below. The operations are performed from the Debug console in the Tools menu."))
        self.label_12.setText(_translate("RegMasternodeDlg", "<b>1. Enter the funding address from your Firo Core wallet:</b>"))
        self.edtManualFundingAddress.setToolTip(_translate("RegMasternodeDlg", "<html><head/><body><p>Enter the address from your Firo Core wallet that has sufficient funds to cover transaction fees.<br><br>You can check the balances of individual addresses by entering the following command in the debug console: <code>listaddressbalances</code>.</p></body></html>"))
        self.btnManualFundingAddressPaste.setToolTip(_translate("RegMasternodeDlg", "Paste text from clipboard"))
        self.label_13.setText(_translate("RegMasternodeDlg", "<b>2. Execute the following command in the Firo wallet\'s debug console:</b>"))
        self.btnManualProtxPrepareCopy.setToolTip(_translate("RegMasternodeDlg", "Copy text to clipboard"))
        self.label_14.setText(_translate("RegMasternodeDlg", "<b>3. Paste the result below and click the &lt;Sign message...&gt; button:</b>"))
        self.btnManualProtxPrepareResultPaste.setToolTip(_translate("RegMasternodeDlg", "Paste text from clipboard"))
        self.btnManualSignProtx.setText(_translate("RegMasternodeDlg", "Sign message with hardware wallet"))
        self.label_17.setText(_translate("RegMasternodeDlg", "<b>4. Execute the following command in the Firo wallet\'s debug console:</b>"))
        self.btnManualProtxSubmitCopy.setToolTip(_translate("RegMasternodeDlg", "Copy text to clipboard"))
        self.label_11.setText(_translate("RegMasternodeDlg", "<b>5. Paste the result (tx hash) below and click the &lt;Continue&gt; button:</b>"))
        self.btnManualTxHashPaste.setToolTip(_translate("RegMasternodeDlg", "Paste text from clipboard"))
        self.lblProtxSummary1.setText(_translate("RegMasternodeDlg", "<b><span style=\"color:green\">Congratultions! The transaction for your DIP-3 masternode has been submitted.</b></span>"))
        self.lblProtxSummary2.setText(_translate("RegMasternodeDlg", "It is highly recommended to make a secure copy of the following information (<a href=\"save\">save to a file</a>):"))
        self.lblProtxSummary3.setText(_translate("RegMasternodeDlg", "..."))
        self.btnSummaryDMNOperatorKeyCopy.setToolTip(_translate("RegMasternodeDlg", "Copy text to clipboard"))
        self.btnCancel.setText(_translate("RegMasternodeDlg", "Cancel"))
        self.lblFieldHints.setText(_translate("RegMasternodeDlg", "Hide field descriptions"))
        self.btnBack.setText(_translate("RegMasternodeDlg", "Back"))
        self.btnContinue.setText(_translate("RegMasternodeDlg", "Continue"))
        self.btnClose.setText(_translate("RegMasternodeDlg", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegMasternodeDlg = QtWidgets.QDialog()
    ui = Ui_RegMasternodeDlg()
    ui.setupUi(RegMasternodeDlg)
    RegMasternodeDlg.show()
    sys.exit(app.exec_())
