# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file ui_recover_hw_wdg.ui
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WdgRecoverHw(object):
    def setupUi(self, WdgRecoverHw):
        WdgRecoverHw.setObjectName("WdgRecoverHw")
        WdgRecoverHw.resize(523, 322)

        self.retranslateUi(WdgRecoverHw)
        QtCore.QMetaObject.connectSlotsByName(WdgRecoverHw)

    def retranslateUi(self, WdgRecoverHw):
        _translate = QtCore.QCoreApplication.translate
        WdgRecoverHw.setWindowTitle(_translate("WdgRecoverHw", "Form"))
