# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'X:\src\ui\ui_send_payout_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SendPayoutDlg(object):
    def setupUi(self, SendPayoutDlg):
        SendPayoutDlg.setObjectName("SendPayoutDlg")
        SendPayoutDlg.resize(632, 444)
        SendPayoutDlg.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SendPayoutDlg)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(SendPayoutDlg)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 8, -1, -1)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCheckAll = QtWidgets.QToolButton(SendPayoutDlg)
        self.btnCheckAll.setText("")
        self.btnCheckAll.setIconSize(QtCore.QSize(12, 12))
        self.btnCheckAll.setObjectName("btnCheckAll")
        self.horizontalLayout.addWidget(self.btnCheckAll)
        self.btnUncheckAll = QtWidgets.QToolButton(SendPayoutDlg)
        self.btnUncheckAll.setText("")
        self.btnUncheckAll.setIconSize(QtCore.QSize(12, 12))
        self.btnUncheckAll.setObjectName("btnUncheckAll")
        self.horizontalLayout.addWidget(self.btnUncheckAll)
        self.chbHideCollateralTx = QtWidgets.QCheckBox(SendPayoutDlg)
        self.chbHideCollateralTx.setStyleSheet("margin-left:20px")
        self.chbHideCollateralTx.setObjectName("chbHideCollateralTx")
        self.horizontalLayout.addWidget(self.chbHideCollateralTx)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(SendPayoutDlg)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setShowGrid(True)
        self.tableView.setSortingEnabled(False)
        self.tableView.setObjectName("tableView")
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.verticalHeader().setCascadingSectionResizes(True)
        self.tableView.verticalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 4, -1, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblAmountText = QtWidgets.QLabel(SendPayoutDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmountText.sizePolicy().hasHeightForWidth())
        self.lblAmountText.setSizePolicy(sizePolicy)
        self.lblAmountText.setObjectName("lblAmountText")
        self.horizontalLayout_2.addWidget(self.lblAmountText)
        self.lblAmount = QtWidgets.QLabel(SendPayoutDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmount.sizePolicy().hasHeightForWidth())
        self.lblAmount.setSizePolicy(sizePolicy)
        self.lblAmount.setObjectName("lblAmount")
        self.horizontalLayout_2.addWidget(self.lblAmount)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(SendPayoutDlg)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.edtDestAddress = QtWidgets.QLineEdit(SendPayoutDlg)
        self.edtDestAddress.setObjectName("edtDestAddress")
        self.horizontalLayout_4.addWidget(self.edtDestAddress)
        self.label_2 = QtWidgets.QLabel(SendPayoutDlg)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.edtTxFee = QtWidgets.QDoubleSpinBox(SendPayoutDlg)
        self.edtTxFee.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edtTxFee.setDecimals(5)
        self.edtTxFee.setMaximum(1.0)
        self.edtTxFee.setSingleStep(0.0001)
        self.edtTxFee.setObjectName("edtTxFee")
        self.horizontalLayout_4.addWidget(self.edtTxFee)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btnSend = QtWidgets.QPushButton(SendPayoutDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSend.sizePolicy().hasHeightForWidth())
        self.btnSend.setSizePolicy(sizePolicy)
        self.btnSend.setMinimumSize(QtCore.QSize(200, 0))
        self.btnSend.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnSend.setAutoDefault(False)
        self.btnSend.setObjectName("btnSend")
        self.horizontalLayout_3.addWidget(self.btnSend)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnClose = QtWidgets.QPushButton(SendPayoutDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        self.btnClose.setMinimumSize(QtCore.QSize(0, 0))
        self.btnClose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnClose.setAutoDefault(False)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_3.addWidget(self.btnClose, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(SendPayoutDlg)
        QtCore.QMetaObject.connectSlotsByName(SendPayoutDlg)

    def retranslateUi(self, SendPayoutDlg):
        _translate = QtCore.QCoreApplication.translate
        SendPayoutDlg.setWindowTitle(_translate("SendPayoutDlg", "Dialog"))
        self.label_3.setText(_translate("SendPayoutDlg", "List of unspent transaction outputs (UTXO) assigned to Masternode addresses. You can transfer all or selected outputs to a new Dash address."))
        self.btnCheckAll.setToolTip(_translate("SendPayoutDlg", "Check all utxos"))
        self.btnUncheckAll.setToolTip(_translate("SendPayoutDlg", "Uncheck all utxos"))
        self.chbHideCollateralTx.setText(_translate("SendPayoutDlg", "Hide collateral utxos"))
        self.lblAmountText.setText(_translate("SendPayoutDlg", "Amount to send:"))
        self.lblAmount.setText(_translate("SendPayoutDlg", "0"))
        self.label.setText(_translate("SendPayoutDlg", "Send to address:"))
        self.label_2.setText(_translate("SendPayoutDlg", "Fee (Dash):"))
        self.btnSend.setText(_translate("SendPayoutDlg", "Send"))
        self.btnClose.setText(_translate("SendPayoutDlg", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SendPayoutDlg = QtWidgets.QDialog()
    ui = Ui_SendPayoutDlg()
    ui.setupUi(SendPayoutDlg)
    SendPayoutDlg.show()
    sys.exit(app.exec_())

