# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/blogin/Projects/dash-masternode-tool/src/ui/ui_upd_mn_service_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UpdMnServiceDlg(object):
    def setupUi(self, UpdMnServiceDlg):
        UpdMnServiceDlg.setObjectName("UpdMnServiceDlg")
        UpdMnServiceDlg.resize(600, 311)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UpdMnServiceDlg.sizePolicy().hasHeightForWidth())
        UpdMnServiceDlg.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(UpdMnServiceDlg)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(UpdMnServiceDlg)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(UpdMnServiceDlg)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.stackedWidget = QtWidgets.QStackedWidget(UpdMnServiceDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page0.sizePolicy().hasHeightForWidth())
        self.page0.setSizePolicy(sizePolicy)
        self.page0.setObjectName("page0")
        self.gridLayout = QtWidgets.QGridLayout(self.page0)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.lblOperatorPayout = QtWidgets.QLabel(self.page0)
        self.lblOperatorPayout.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOperatorPayout.setObjectName("lblOperatorPayout")
        self.gridLayout.addWidget(self.lblOperatorPayout, 2, 0, 1, 1)
        self.layOperatorPayout = QtWidgets.QHBoxLayout()
        self.layOperatorPayout.setSpacing(8)
        self.layOperatorPayout.setObjectName("layOperatorPayout")
        self.edtOperatorPayoutAddress = QtWidgets.QLineEdit(self.page0)
        self.edtOperatorPayoutAddress.setPlaceholderText("")
        self.edtOperatorPayoutAddress.setClearButtonEnabled(True)
        self.edtOperatorPayoutAddress.setObjectName("edtOperatorPayoutAddress")
        self.layOperatorPayout.addWidget(self.edtOperatorPayoutAddress)
        self.gridLayout.addLayout(self.layOperatorPayout, 2, 1, 1, 1)
        self.lblIP = QtWidgets.QLabel(self.page0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblIP.setFont(font)
        self.lblIP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIP.setObjectName("lblIP")
        self.gridLayout.addWidget(self.lblIP, 1, 0, 1, 1)
        self.lblOperatorPayoutMsg = QtWidgets.QLabel(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOperatorPayoutMsg.sizePolicy().hasHeightForWidth())
        self.lblOperatorPayoutMsg.setSizePolicy(sizePolicy)
        self.lblOperatorPayoutMsg.setText("")
        self.lblOperatorPayoutMsg.setWordWrap(True)
        self.lblOperatorPayoutMsg.setOpenExternalLinks(True)
        self.lblOperatorPayoutMsg.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblOperatorPayoutMsg.setObjectName("lblOperatorPayoutMsg")
        self.gridLayout.addWidget(self.lblOperatorPayoutMsg, 3, 1, 1, 1)
        self.layPayoutAddress = QtWidgets.QHBoxLayout()
        self.layPayoutAddress.setSpacing(8)
        self.layPayoutAddress.setObjectName("layPayoutAddress")
        self.edtIP = QtWidgets.QLineEdit(self.page0)
        self.edtIP.setPlaceholderText("")
        self.edtIP.setClearButtonEnabled(True)
        self.edtIP.setObjectName("edtIP")
        self.layPayoutAddress.addWidget(self.edtIP)
        self.label_2 = QtWidgets.QLabel(self.page0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.layPayoutAddress.addWidget(self.label_2)
        self.edtPort = QtWidgets.QLineEdit(self.page0)
        self.edtPort.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edtPort.setClearButtonEnabled(True)
        self.edtPort.setObjectName("edtPort")
        self.layPayoutAddress.addWidget(self.edtPort)
        self.gridLayout.addLayout(self.layPayoutAddress, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page0)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.line = QtWidgets.QFrame(UpdMnServiceDlg)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.lblManualCommands = QtWidgets.QLabel(UpdMnServiceDlg)
        self.lblManualCommands.setText("")
        self.lblManualCommands.setObjectName("lblManualCommands")
        self.verticalLayout.addWidget(self.lblManualCommands)
        self.edtManualCommands = QtWidgets.QTextBrowser(UpdMnServiceDlg)
        self.edtManualCommands.setOpenExternalLinks(True)
        self.edtManualCommands.setOpenLinks(True)
        self.edtManualCommands.setObjectName("edtManualCommands")
        self.verticalLayout.addWidget(self.edtManualCommands)
        self.frame = QtWidgets.QFrame(UpdMnServiceDlg)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(self.frame)
        self.btnCancel.setAutoDefault(False)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.lblDocumentation = QtWidgets.QLabel(self.frame)
        self.lblDocumentation.setText("")
        self.lblDocumentation.setOpenExternalLinks(True)
        self.lblDocumentation.setObjectName("lblDocumentation")
        self.horizontalLayout.addWidget(self.lblDocumentation)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnSendUpdateTx = QtWidgets.QPushButton(self.frame)
        self.btnSendUpdateTx.setAutoDefault(False)
        self.btnSendUpdateTx.setObjectName("btnSendUpdateTx")
        self.horizontalLayout.addWidget(self.btnSendUpdateTx)
        self.btnClose = QtWidgets.QPushButton(self.frame)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(UpdMnServiceDlg)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UpdMnServiceDlg)
        UpdMnServiceDlg.setTabOrder(self.edtIP, self.edtPort)
        UpdMnServiceDlg.setTabOrder(self.edtPort, self.edtOperatorPayoutAddress)
        UpdMnServiceDlg.setTabOrder(self.edtOperatorPayoutAddress, self.edtManualCommands)
        UpdMnServiceDlg.setTabOrder(self.edtManualCommands, self.btnSendUpdateTx)
        UpdMnServiceDlg.setTabOrder(self.btnSendUpdateTx, self.btnClose)
        UpdMnServiceDlg.setTabOrder(self.btnClose, self.btnCancel)

    def retranslateUi(self, UpdMnServiceDlg):
        _translate = QtCore.QCoreApplication.translate
        UpdMnServiceDlg.setWindowTitle(_translate("UpdMnServiceDlg", "Update service"))
        self.label.setText(_translate("UpdMnServiceDlg", "The transaction type associated with this action (ProUpServTx) is used to update information relating to the operator (<a href=\"https://docs.dash.org/en/stable/masternodes/maintenance.html#proupservtx\">details</a>)."))
        self.lblOperatorPayout.setText(_translate("UpdMnServiceDlg", "<b>Operator Payout address</b> "))
        self.lblIP.setText(_translate("UpdMnServiceDlg", "IP"))
        self.label_2.setText(_translate("UpdMnServiceDlg", "Port"))
        self.btnCancel.setText(_translate("UpdMnServiceDlg", "Cancel"))
        self.btnSendUpdateTx.setText(_translate("UpdMnServiceDlg", "Send Update Transaction"))
        self.btnClose.setText(_translate("UpdMnServiceDlg", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UpdMnServiceDlg = QtWidgets.QDialog()
    ui = Ui_UpdMnServiceDlg()
    ui.setupUi(UpdMnServiceDlg)
    UpdMnServiceDlg.show()
    sys.exit(app.exec_())

