# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file ui_wallet_tools_dlg.ui
#
# Created by: PyQt5 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WalletToolsDlg(object):
    def setupUi(self, WalletToolsDlg):
        WalletToolsDlg.setObjectName("WalletToolsDlg")
        WalletToolsDlg.resize(685, 485)
        self.verticalLayout = QtWidgets.QVBoxLayout(WalletToolsDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(WalletToolsDlg)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.line = QtWidgets.QFrame(WalletToolsDlg)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.tabsMain = QtWidgets.QStackedWidget(WalletToolsDlg)
        self.tabsMain.setObjectName("tabsMain")
        self.tabActionsMenu = QtWidgets.QWidget()
        self.tabActionsMenu.setObjectName("tabActionsMenu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabActionsMenu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbActionsMenu = QtWidgets.QGroupBox(self.tabActionsMenu)
        self.gbActionsMenu.setTitle("")
        self.gbActionsMenu.setObjectName("gbActionsMenu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbActionsMenu)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.actHwSettings = QtWidgets.QCommandLinkButton(self.gbActionsMenu)
        self.actHwSettings.setObjectName("actHwSettings")
        self.verticalLayout_3.addWidget(self.actHwSettings)
        self.actRecoverHw = QtWidgets.QCommandLinkButton(self.gbActionsMenu)
        self.actRecoverHw.setObjectName("actRecoverHw")
        self.verticalLayout_3.addWidget(self.actRecoverHw)
        self.actInitializeHw = QtWidgets.QCommandLinkButton(self.gbActionsMenu)
        self.actInitializeHw.setObjectName("actInitializeHw")
        self.verticalLayout_3.addWidget(self.actInitializeHw)
        self.actWipeHw = QtWidgets.QCommandLinkButton(self.gbActionsMenu)
        self.actWipeHw.setObjectName("actWipeHw")
        self.verticalLayout_3.addWidget(self.actWipeHw)
        self.actUpdateHwFirmware = QtWidgets.QCommandLinkButton(self.gbActionsMenu)
        self.actUpdateHwFirmware.setObjectName("actUpdateHwFirmware")
        self.verticalLayout_3.addWidget(self.actUpdateHwFirmware)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.gbActionsMenu)
        self.tabsMain.addWidget(self.tabActionsMenu)
        self.tabActionContainer = QtWidgets.QWidget()
        self.tabActionContainer.setObjectName("tabActionContainer")
        self.tabsMain.addWidget(self.tabActionContainer)
        self.verticalLayout.addWidget(self.tabsMain)
        self.widget = QtWidgets.QWidget(WalletToolsDlg)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(self.widget)
        self.btnCancel.setAutoDefault(False)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnBack = QtWidgets.QPushButton(self.widget)
        self.btnBack.setAutoDefault(False)
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout.addWidget(self.btnBack)
        self.btnContinue = QtWidgets.QPushButton(self.widget)
        self.btnContinue.setAutoDefault(False)
        self.btnContinue.setObjectName("btnContinue")
        self.horizontalLayout.addWidget(self.btnContinue)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(WalletToolsDlg)
        self.tabsMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WalletToolsDlg)

    def retranslateUi(self, WalletToolsDlg):
        _translate = QtCore.QCoreApplication.translate
        WalletToolsDlg.setWindowTitle(_translate("WalletToolsDlg", "Dialog"))
        self.lblTitle.setText(_translate("WalletToolsDlg", "<b>Choose action</b>"))
        self.actHwSettings.setText(_translate("WalletToolsDlg", "Hardware wallet settings"))
        self.actRecoverHw.setText(_translate("WalletToolsDlg", "Recover hardware wallet from seed"))
        self.actInitializeHw.setText(_translate("WalletToolsDlg", "Initialize hardware wallet with newly generated seed"))
        self.actWipeHw.setText(_translate("WalletToolsDlg", "Wipe hardware wallet"))
        self.actUpdateHwFirmware.setText(_translate("WalletToolsDlg", "Update hardware wallet firmware"))
        self.btnCancel.setText(_translate("WalletToolsDlg", "Cancel"))
        self.btnBack.setText(_translate("WalletToolsDlg", "Back"))
        self.btnContinue.setText(_translate("WalletToolsDlg", "Continue"))
