# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/blogin/PycharmProjects/DMT-git/src/ui/ui_wallet_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WalletDlg(object):
    def setupUi(self, WalletDlg):
        WalletDlg.setObjectName("WalletDlg")
        WalletDlg.resize(862, 630)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WalletDlg.sizePolicy().hasHeightForWidth())
        WalletDlg.setSizePolicy(sizePolicy)
        WalletDlg.setSizeGripEnabled(True)
        WalletDlg.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(WalletDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pnl_input = QtWidgets.QWidget(WalletDlg)
        self.pnl_input.setObjectName("pnl_input")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pnl_input)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lay_input = QtWidgets.QHBoxLayout()
        self.lay_input.setSpacing(8)
        self.lay_input.setObjectName("lay_input")
        self.btnReconnectHW = QtWidgets.QPushButton(self.pnl_input)
        self.btnReconnectHW.setAutoDefault(False)
        self.btnReconnectHW.setObjectName("btnReconnectHW")
        self.lay_input.addWidget(self.btnReconnectHW)
        self.btnLoadTransactions = QtWidgets.QPushButton(self.pnl_input)
        self.btnLoadTransactions.setAutoDefault(False)
        self.btnLoadTransactions.setObjectName("btnLoadTransactions")
        self.lay_input.addWidget(self.btnLoadTransactions)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lay_input.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.lay_input)
        self.verticalLayout.addWidget(self.pnl_input)
        self.widget = QtWidgets.QWidget(WalletDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitterMain = QtWidgets.QSplitter(self.widget)
        self.splitterMain.setOrientation(QtCore.Qt.Horizontal)
        self.splitterMain.setOpaqueResize(True)
        self.splitterMain.setChildrenCollapsible(True)
        self.splitterMain.setObjectName("splitterMain")
        self.widget_2 = QtWidgets.QWidget(self.splitterMain)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cboAddressSourceMode = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboAddressSourceMode.sizePolicy().hasHeightForWidth())
        self.cboAddressSourceMode.setSizePolicy(sizePolicy)
        self.cboAddressSourceMode.setMinimumSize(QtCore.QSize(0, 0))
        self.cboAddressSourceMode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cboAddressSourceMode.setObjectName("cboAddressSourceMode")
        self.cboAddressSourceMode.addItem("")
        self.cboAddressSourceMode.addItem("")
        self.verticalLayout_7.addWidget(self.cboAddressSourceMode)
        self.swAddressSource = QtWidgets.QStackedWidget(self.widget_2)
        self.swAddressSource.setObjectName("swAddressSource")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.accountsListView = QtWidgets.QTreeView(self.page)
        self.accountsListView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.accountsListView.setObjectName("accountsListView")
        self.accountsListView.header().setVisible(False)
        self.verticalLayout_8.addWidget(self.accountsListView)
        self.swAddressSource.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.mnListView = QtWidgets.QTableView(self.page_2)
        self.mnListView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.mnListView.setShowGrid(False)
        self.mnListView.setObjectName("mnListView")
        self.mnListView.horizontalHeader().setVisible(False)
        self.mnListView.horizontalHeader().setStretchLastSection(True)
        self.mnListView.verticalHeader().setVisible(False)
        self.verticalLayout_10.addWidget(self.mnListView)
        self.swAddressSource.addWidget(self.page_2)
        self.verticalLayout_7.addWidget(self.swAddressSource)
        self.widget_3 = QtWidgets.QWidget(self.splitterMain)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_3)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_send = QtWidgets.QWidget()
        self.tab_send.setObjectName("tab_send")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_send)
        self.verticalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtWidgets.QSplitter(self.tab_send)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.main_widget = QtWidgets.QWidget(self.splitter)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 8, -1, -1)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnCheckAll = QtWidgets.QToolButton(self.main_widget)
        self.btnCheckAll.setToolTip("")
        self.btnCheckAll.setIconSize(QtCore.QSize(12, 12))
        self.btnCheckAll.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnCheckAll.setObjectName("btnCheckAll")
        self.horizontalLayout_4.addWidget(self.btnCheckAll)
        self.btnUncheckAll = QtWidgets.QToolButton(self.main_widget)
        self.btnUncheckAll.setToolTip("")
        self.btnUncheckAll.setIconSize(QtCore.QSize(12, 12))
        self.btnUncheckAll.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnUncheckAll.setObjectName("btnUncheckAll")
        self.horizontalLayout_4.addWidget(self.btnUncheckAll)
        self.btnUtxoViewColumns = QtWidgets.QToolButton(self.main_widget)
        self.btnUtxoViewColumns.setObjectName("btnUtxoViewColumns")
        self.horizontalLayout_4.addWidget(self.btnUtxoViewColumns)
        self.chbHideCollateralTx = QtWidgets.QCheckBox(self.main_widget)
        self.chbHideCollateralTx.setStyleSheet("")
        self.chbHideCollateralTx.setObjectName("chbHideCollateralTx")
        self.horizontalLayout_4.addWidget(self.chbHideCollateralTx)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.utxoTableView = QtWidgets.QTableView(self.main_widget)
        self.utxoTableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.utxoTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.utxoTableView.setShowGrid(True)
        self.utxoTableView.setSortingEnabled(False)
        self.utxoTableView.setObjectName("utxoTableView")
        self.utxoTableView.verticalHeader().setVisible(False)
        self.utxoTableView.verticalHeader().setCascadingSectionResizes(True)
        self.utxoTableView.verticalHeader().setHighlightSections(False)
        self.verticalLayout_2.addWidget(self.utxoTableView)
        self.dest_widget1 = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dest_widget1.sizePolicy().hasHeightForWidth())
        self.dest_widget1.setSizePolicy(sizePolicy)
        self.dest_widget1.setObjectName("dest_widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dest_widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dest_widget = QtWidgets.QFrame(self.dest_widget1)
        self.dest_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dest_widget.setObjectName("dest_widget")
        self.verticalLayout_3.addWidget(self.dest_widget)
        self.verticalLayout_5.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab_send, "")
        self.tab_transactions = QtWidgets.QWidget()
        self.tab_transactions.setObjectName("tab_transactions")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_transactions)
        self.horizontalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabViewTransactions = QtWidgets.QTableView(self.tab_transactions)
        self.tabViewTransactions.setObjectName("tabViewTransactions")
        self.horizontalLayout_5.addWidget(self.tabViewTransactions)
        self.tabWidget.addTab(self.tab_transactions, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        self.verticalLayout_6.addWidget(self.splitterMain)
        self.verticalLayout.addWidget(self.widget)
        self.layStatusBar = QtWidgets.QHBoxLayout()
        self.layStatusBar.setSpacing(12)
        self.layStatusBar.setObjectName("layStatusBar")
        self.lbl_message = QtWidgets.QLabel(WalletDlg)
        self.lbl_message.setStyleSheet("")
        self.lbl_message.setText("")
        self.lbl_message.setWordWrap(False)
        self.lbl_message.setOpenExternalLinks(True)
        self.lbl_message.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lbl_message.setObjectName("lbl_message")
        self.layStatusBar.addWidget(self.lbl_message)
        self.lbl_message_2 = QtWidgets.QLabel(WalletDlg)
        self.lbl_message_2.setText("")
        self.lbl_message_2.setOpenExternalLinks(True)
        self.lbl_message_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lbl_message_2.setObjectName("lbl_message_2")
        self.layStatusBar.addWidget(self.lbl_message_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layStatusBar.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.layStatusBar)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btnSend = QtWidgets.QPushButton(WalletDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSend.sizePolicy().hasHeightForWidth())
        self.btnSend.setSizePolicy(sizePolicy)
        self.btnSend.setMinimumSize(QtCore.QSize(200, 0))
        self.btnSend.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnSend.setAutoDefault(False)
        self.btnSend.setObjectName("btnSend")
        self.horizontalLayout_3.addWidget(self.btnSend)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btnClose = QtWidgets.QPushButton(WalletDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        self.btnClose.setMinimumSize(QtCore.QSize(0, 0))
        self.btnClose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnClose.setAutoDefault(False)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_3.addWidget(self.btnClose, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(WalletDlg)
        self.swAddressSource.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WalletDlg)

    def retranslateUi(self, WalletDlg):
        _translate = QtCore.QCoreApplication.translate
        WalletDlg.setWindowTitle(_translate("WalletDlg", "Dialog"))
        self.btnReconnectHW.setText(_translate("WalletDlg", "Reconnect Hardware Wallet"))
        self.btnLoadTransactions.setText(_translate("WalletDlg", "Reload transactions"))
        self.cboAddressSourceMode.setItemText(0, _translate("WalletDlg", "View As: Wallet Account"))
        self.cboAddressSourceMode.setItemText(1, _translate("WalletDlg", "View As: Masternode Address"))
        self.btnCheckAll.setText(_translate("WalletDlg", "Select All"))
        self.btnUncheckAll.setText(_translate("WalletDlg", "Unselect All"))
        self.btnUtxoViewColumns.setText(_translate("WalletDlg", "Columns..."))
        self.chbHideCollateralTx.setText(_translate("WalletDlg", "Hide collateral utxos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_send), _translate("WalletDlg", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_transactions), _translate("WalletDlg", "Transactions"))
        self.btnSend.setText(_translate("WalletDlg", "Prepare Transaction"))
        self.btnClose.setText(_translate("WalletDlg", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WalletDlg = QtWidgets.QDialog()
    ui = Ui_WalletDlg()
    ui.setupUi(WalletDlg)
    WalletDlg.show()
    sys.exit(app.exec_())

