# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/wnd_trezor_pin_base.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogTrezorPin(object):
    def setupUi(self, DialogTrezorPin):
        DialogTrezorPin.setObjectName("DialogTrezorPin")
        DialogTrezorPin.resize(236, 332)
        DialogTrezorPin.setMinimumSize(QtCore.QSize(0, 0))
        DialogTrezorPin.setMaximumSize(QtCore.QSize(300, 400))
        DialogTrezorPin.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogTrezorPin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblMessage = QtWidgets.QLabel(DialogTrezorPin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMessage.sizePolicy().hasHeightForWidth())
        self.lblMessage.setSizePolicy(sizePolicy)
        self.lblMessage.setObjectName("lblMessage")
        self.verticalLayout.addWidget(self.lblMessage)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.btnPin1 = QtWidgets.QPushButton(DialogTrezorPin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPin1.sizePolicy().hasHeightForWidth())
        self.btnPin1.setSizePolicy(sizePolicy)
        self.btnPin1.setMinimumSize(QtCore.QSize(70, 70))
        self.btnPin1.setMaximumSize(QtCore.QSize(70, 70))
        self.btnPin1.setAutoDefault(False)
        self.btnPin1.setObjectName("btnPin1")
        self.gridLayout.addWidget(self.btnPin1, 2, 0, 1, 1)
        self.btnPin6 = QtWidgets.QPushButton(DialogTrezorPin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPin6.sizePolicy().hasHeightForWidth())
        self.btnPin6.setSizePolicy(sizePolicy)
        self.btnPin6.setMinimumSize(QtCore.QSize(70, 70))
        self.btnPin6.setMaximumSize(QtCore.QSize(70, 70))
        self.btnPin6.setAutoDefault(False)
        self.btnPin6.setObjectName("btnPin6")
        self.gridLayout.addWidget(self.btnPin6, 1, 2, 1, 1)
        self.btnPin5 = QtWidgets.QPushButton(DialogTrezorPin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPin5.sizePolicy().hasHeightForWidth())
        self.btnPin5.setSizePolicy(sizePolicy)
        self.btnPin5.setMinimumSize(QtCore.QSize(70, 70))
        self.btnPin5.setMaximumSize(QtCore.QSize(70, 70))
        self.btnPin5.setAutoDefault(False)
        self.btnPin5.setObjectName("btnPin5")
        self.gridLayout.addWidget(self.btnPin5, 1, 1, 1, 1)
        self.btnPin4 = QtWidgets.QPushButton(DialogTrezorPin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPin4.sizePolicy().hasHeightForWidth())
        self.btnPin4.setSizePolicy(sizePolicy)
        self.btnPin4.setMinimumSize(QtCore.QSize(70, 70))
        self.btnPin4.setMaximumSize(QtCore.QSize(70, 70))
        self.btnPin4.setAutoDefault(False)
        self.btnPin4.setObjectName("btnPin4")
        self.gridLayout.addWidget(self.btnPin4, 1, 0, 1, 1)
        self.btnPin7 = QtWidgets.QPushButton(DialogTrezorPin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPin7.sizePolicy().hasHeightForWidth())
        self.btnPin7.setSizePolicy(sizePolicy)
        self.btnPin7.setMinimumSize(QtCore.QSize(70, 70))
        self.btnPin7.setMaximumSize(QtCore.QSize(70, 70))
        self.btnPin7.setAutoDefault(False)
        self.btnPin7.setFlat(False)
        self.btnPin7.setObjectName("btnPin7")
        self.gridLayout.addWidget(self.btnPin7, 0, 0, 1, 1)
        self.btnPin2 = QtWidgets.QPushButton(DialogTrezorPin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPin2.sizePolicy().hasHeightForWidth())
        self.btnPin2.setSizePolicy(sizePolicy)
        self.btnPin2.setMinimumSize(QtCore.QSize(70, 70))
        self.btnPin2.setMaximumSize(QtCore.QSize(70, 70))
        self.btnPin2.setAutoDefault(False)
        self.btnPin2.setObjectName("btnPin2")
        self.gridLayout.addWidget(self.btnPin2, 2, 1, 1, 1)
        self.btnPin8 = QtWidgets.QPushButton(DialogTrezorPin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPin8.sizePolicy().hasHeightForWidth())
        self.btnPin8.setSizePolicy(sizePolicy)
        self.btnPin8.setMinimumSize(QtCore.QSize(70, 70))
        self.btnPin8.setMaximumSize(QtCore.QSize(70, 70))
        self.btnPin8.setAutoDefault(False)
        self.btnPin8.setFlat(False)
        self.btnPin8.setObjectName("btnPin8")
        self.gridLayout.addWidget(self.btnPin8, 0, 1, 1, 1)
        self.btnPin3 = QtWidgets.QPushButton(DialogTrezorPin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPin3.sizePolicy().hasHeightForWidth())
        self.btnPin3.setSizePolicy(sizePolicy)
        self.btnPin3.setMinimumSize(QtCore.QSize(70, 70))
        self.btnPin3.setMaximumSize(QtCore.QSize(70, 70))
        self.btnPin3.setAutoDefault(False)
        self.btnPin3.setObjectName("btnPin3")
        self.gridLayout.addWidget(self.btnPin3, 2, 2, 1, 1)
        self.btnPin9 = QtWidgets.QPushButton(DialogTrezorPin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPin9.sizePolicy().hasHeightForWidth())
        self.btnPin9.setSizePolicy(sizePolicy)
        self.btnPin9.setMinimumSize(QtCore.QSize(70, 70))
        self.btnPin9.setMaximumSize(QtCore.QSize(70, 70))
        self.btnPin9.setAutoDefault(False)
        self.btnPin9.setObjectName("btnPin9")
        self.gridLayout.addWidget(self.btnPin9, 0, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edtPin = QtWidgets.QLineEdit(DialogTrezorPin)
        self.edtPin.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPin.sizePolicy().hasHeightForWidth())
        self.edtPin.setSizePolicy(sizePolicy)
        self.edtPin.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edtPin.setFont(font)
        self.edtPin.setFrame(True)
        self.edtPin.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edtPin.setObjectName("edtPin")
        self.horizontalLayout.addWidget(self.edtPin)
        self.btnDelete = QtWidgets.QToolButton(DialogTrezorPin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelete.sizePolicy().hasHeightForWidth())
        self.btnDelete.setSizePolicy(sizePolicy)
        self.btnDelete.setMinimumSize(QtCore.QSize(40, 26))
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout.addWidget(self.btnDelete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btnEnterPin = QtWidgets.QPushButton(DialogTrezorPin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEnterPin.sizePolicy().hasHeightForWidth())
        self.btnEnterPin.setSizePolicy(sizePolicy)
        self.btnEnterPin.setMinimumSize(QtCore.QSize(0, 31))
        self.btnEnterPin.setObjectName("btnEnterPin")
        self.verticalLayout.addWidget(self.btnEnterPin)

        self.retranslateUi(DialogTrezorPin)
        QtCore.QMetaObject.connectSlotsByName(DialogTrezorPin)

    def retranslateUi(self, DialogTrezorPin):
        _translate = QtCore.QCoreApplication.translate
        DialogTrezorPin.setWindowTitle(_translate("DialogTrezorPin", "Dialog"))
        self.lblMessage.setText(_translate("DialogTrezorPin", "Enter PIN"))
        self.btnPin1.setText(_translate("DialogTrezorPin", "*"))
        self.btnPin6.setText(_translate("DialogTrezorPin", "*"))
        self.btnPin5.setText(_translate("DialogTrezorPin", "*"))
        self.btnPin4.setText(_translate("DialogTrezorPin", "*"))
        self.btnPin7.setText(_translate("DialogTrezorPin", "*"))
        self.btnPin2.setText(_translate("DialogTrezorPin", "*"))
        self.btnPin8.setText(_translate("DialogTrezorPin", "*"))
        self.btnPin3.setText(_translate("DialogTrezorPin", "*"))
        self.btnPin9.setText(_translate("DialogTrezorPin", "*"))
        self.btnDelete.setToolTip(_translate("DialogTrezorPin", "Delete last character"))
        self.btnDelete.setText(_translate("DialogTrezorPin", "<- Del"))
        self.btnEnterPin.setText(_translate("DialogTrezorPin", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogTrezorPin = QtWidgets.QDialog()
    ui = Ui_DialogTrezorPin()
    ui.setupUi(DialogTrezorPin)
    DialogTrezorPin.show()
    sys.exit(app.exec_())

