# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/wnd_conn_base.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogConnection(object):
    def setupUi(self, DialogConnection):
        DialogConnection.setObjectName("DialogConnection")
        DialogConnection.resize(533, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogConnection.sizePolicy().hasHeightForWidth())
        DialogConnection.setSizePolicy(sizePolicy)
        DialogConnection.setSizeGripEnabled(True)
        DialogConnection.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogConnection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabConnectMethod = QtWidgets.QTabWidget(DialogConnection)
        self.tabConnectMethod.setObjectName("tabConnectMethod")
        self.tabDashDaemon = QtWidgets.QWidget()
        self.tabDashDaemon.setObjectName("tabDashDaemon")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabDashDaemon)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.edtRpcUsername = QtWidgets.QLineEdit(self.tabDashDaemon)
        self.edtRpcUsername.setObjectName("edtRpcUsername")
        self.gridLayout.addWidget(self.edtRpcUsername, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tabDashDaemon)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.edtRpcPassword = QtWidgets.QLineEdit(self.tabDashDaemon)
        self.edtRpcPassword.setObjectName("edtRpcPassword")
        self.gridLayout.addWidget(self.edtRpcPassword, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tabDashDaemon)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tabDashDaemon)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edtRpcIP = QtWidgets.QLineEdit(self.tabDashDaemon)
        self.edtRpcIP.setObjectName("edtRpcIP")
        self.horizontalLayout.addWidget(self.edtRpcIP)
        self.label_11 = QtWidgets.QLabel(self.tabDashDaemon)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.edtRpcPort = QtWidgets.QLineEdit(self.tabDashDaemon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRpcPort.sizePolicy().hasHeightForWidth())
        self.edtRpcPort.setSizePolicy(sizePolicy)
        self.edtRpcPort.setMaximumSize(QtCore.QSize(50, 16777215))
        self.edtRpcPort.setObjectName("edtRpcPort")
        self.horizontalLayout.addWidget(self.edtRpcPort)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.tabConnectMethod.addTab(self.tabDashDaemon, "")
        self.tabDashDaemonSSH = QtWidgets.QWidget()
        self.tabDashDaemonSSH.setObjectName("tabDashDaemonSSH")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabDashDaemonSSH)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.edtRosRpcBindIp = QtWidgets.QLineEdit(self.tabDashDaemonSSH)
        self.edtRosRpcBindIp.setObjectName("edtRosRpcBindIp")
        self.horizontalLayout_6.addWidget(self.edtRosRpcBindIp)
        self.label_8 = QtWidgets.QLabel(self.tabDashDaemonSSH)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.edtRosRpcBindPort = QtWidgets.QLineEdit(self.tabDashDaemonSSH)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRosRpcBindPort.sizePolicy().hasHeightForWidth())
        self.edtRosRpcBindPort.setSizePolicy(sizePolicy)
        self.edtRosRpcBindPort.setMaximumSize(QtCore.QSize(50, 16777215))
        self.edtRosRpcBindPort.setObjectName("edtRosRpcBindPort")
        self.horizontalLayout_6.addWidget(self.edtRosRpcBindPort)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tabDashDaemonSSH)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.edtRosRpcPassword = QtWidgets.QLineEdit(self.tabDashDaemonSSH)
        self.edtRosRpcPassword.setObjectName("edtRosRpcPassword")
        self.gridLayout_2.addWidget(self.edtRosRpcPassword, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 7, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.edtRosSshHost = QtWidgets.QLineEdit(self.tabDashDaemonSSH)
        self.edtRosSshHost.setObjectName("edtRosSshHost")
        self.horizontalLayout_5.addWidget(self.edtRosSshHost)
        self.label_5 = QtWidgets.QLabel(self.tabDashDaemonSSH)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.edtRosSshPort = QtWidgets.QLineEdit(self.tabDashDaemonSSH)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtRosSshPort.sizePolicy().hasHeightForWidth())
        self.edtRosSshPort.setSizePolicy(sizePolicy)
        self.edtRosSshPort.setMaximumSize(QtCore.QSize(50, 16777215))
        self.edtRosSshPort.setObjectName("edtRosSshPort")
        self.horizontalLayout_5.addWidget(self.edtRosSshPort)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tabDashDaemonSSH)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tabDashDaemonSSH)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tabDashDaemonSSH)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.btnRosReadDashdConfig = QtWidgets.QPushButton(self.tabDashDaemonSSH)
        self.btnRosReadDashdConfig.setAutoDefault(False)
        self.btnRosReadDashdConfig.setObjectName("btnRosReadDashdConfig")
        self.gridLayout_2.addWidget(self.btnRosReadDashdConfig, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tabDashDaemonSSH)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.edtRosRpcUsername = QtWidgets.QLineEdit(self.tabDashDaemonSSH)
        self.edtRosRpcUsername.setObjectName("edtRosRpcUsername")
        self.gridLayout_2.addWidget(self.edtRosRpcUsername, 5, 1, 1, 1)
        self.edtRosSshUsername = QtWidgets.QLineEdit(self.tabDashDaemonSSH)
        self.edtRosSshUsername.setObjectName("edtRosSshUsername")
        self.gridLayout_2.addWidget(self.edtRosSshUsername, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.tabConnectMethod.addTab(self.tabDashDaemonSSH, "")
        self.verticalLayout.addWidget(self.tabConnectMethod)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnTestConnection = QtWidgets.QPushButton(DialogConnection)
        self.btnTestConnection.setMinimumSize(QtCore.QSize(120, 0))
        self.btnTestConnection.setAutoDefault(False)
        self.btnTestConnection.setObjectName("btnTestConnection")
        self.horizontalLayout_3.addWidget(self.btnTestConnection)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnCancel = QtWidgets.QPushButton(DialogConnection)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.btnOk = QtWidgets.QPushButton(DialogConnection)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout_3.addWidget(self.btnOk)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(DialogConnection)
        self.tabConnectMethod.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DialogConnection)
        DialogConnection.setTabOrder(self.edtRosSshHost, self.edtRosSshPort)
        DialogConnection.setTabOrder(self.edtRosSshPort, self.edtRosSshUsername)
        DialogConnection.setTabOrder(self.edtRosSshUsername, self.btnRosReadDashdConfig)
        DialogConnection.setTabOrder(self.btnRosReadDashdConfig, self.edtRosRpcBindIp)
        DialogConnection.setTabOrder(self.edtRosRpcBindIp, self.edtRosRpcBindPort)
        DialogConnection.setTabOrder(self.edtRosRpcBindPort, self.edtRosRpcUsername)
        DialogConnection.setTabOrder(self.edtRosRpcUsername, self.edtRosRpcPassword)
        DialogConnection.setTabOrder(self.edtRosRpcPassword, self.edtRpcIP)
        DialogConnection.setTabOrder(self.edtRpcIP, self.edtRpcPort)
        DialogConnection.setTabOrder(self.edtRpcPort, self.edtRpcUsername)
        DialogConnection.setTabOrder(self.edtRpcUsername, self.edtRpcPassword)
        DialogConnection.setTabOrder(self.edtRpcPassword, self.btnTestConnection)
        DialogConnection.setTabOrder(self.btnTestConnection, self.btnOk)
        DialogConnection.setTabOrder(self.btnOk, self.tabConnectMethod)

    def retranslateUi(self, DialogConnection):
        _translate = QtCore.QCoreApplication.translate
        DialogConnection.setWindowTitle(_translate("DialogConnection", "Dialog"))
        self.label_3.setText(_translate("DialogConnection", "RPC password:"))
        self.label_2.setText(_translate("DialogConnection", "RPC username:"))
        self.label.setText(_translate("DialogConnection", "IP:"))
        self.edtRpcIP.setText(_translate("DialogConnection", "127.0.0.1"))
        self.label_11.setText(_translate("DialogConnection", "port:"))
        self.edtRpcPort.setInputMask(_translate("DialogConnection", "D000"))
        self.edtRpcPort.setText(_translate("DialogConnection", "9998"))
        self.tabConnectMethod.setTabText(self.tabConnectMethod.indexOf(self.tabDashDaemon), _translate("DialogConnection", "Dashd direct RPC"))
        self.label_8.setText(_translate("DialogConnection", "port:"))
        self.edtRosRpcBindPort.setInputMask(_translate("DialogConnection", "D000"))
        self.label_6.setText(_translate("DialogConnection", "SSH username:"))
        self.label_5.setText(_translate("DialogConnection", "port:"))
        self.edtRosSshPort.setInputMask(_translate("DialogConnection", "D000"))
        self.label_9.setText(_translate("DialogConnection", "RPC username:"))
        self.label_10.setText(_translate("DialogConnection", "RPC password:"))
        self.label_4.setText(_translate("DialogConnection", "SSH host:"))
        self.btnRosReadDashdConfig.setText(_translate("DialogConnection", "Read RPC configuration from SSH host"))
        self.label_7.setText(_translate("DialogConnection", "RPC bind IP:"))
        self.tabConnectMethod.setTabText(self.tabConnectMethod.indexOf(self.tabDashDaemonSSH), _translate("DialogConnection", "Dashd RPC over SSH tunnel"))
        self.btnTestConnection.setText(_translate("DialogConnection", "Test connection"))
        self.btnCancel.setText(_translate("DialogConnection", "Cancel"))
        self.btnOk.setText(_translate("DialogConnection", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogConnection = QtWidgets.QDialog()
    ui = Ui_DialogConnection()
    ui.setupUi(DialogConnection)
    DialogConnection.show()
    sys.exit(app.exec_())

